//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.TASModuloService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASModuloSet", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASModuloSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity> ltTASModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity> ltTASModuloEliminadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity> ltTASModulo {
            get {
                return this.ltTASModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASModuloField, value) != true)) {
                    this.ltTASModuloField = value;
                    this.RaisePropertyChanged("ltTASModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity> ltTASModuloEliminado {
            get {
                return this.ltTASModuloEliminadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASModuloEliminadoField, value) != true)) {
                    this.ltTASModuloEliminadoField = value;
                    this.RaisePropertyChanged("ltTASModuloEliminado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASModuloEntity", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASModuloEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private adminlte.TASModuloService.Estado UEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool USelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal1 {
            get {
                return this.Decimal1Field;
            }
            set {
                if ((this.Decimal1Field.Equals(value) != true)) {
                    this.Decimal1Field = value;
                    this.RaisePropertyChanged("Decimal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal2 {
            get {
                return this.Decimal2Field;
            }
            set {
                if ((this.Decimal2Field.Equals(value) != true)) {
                    this.Decimal2Field = value;
                    this.RaisePropertyChanged("Decimal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero1 {
            get {
                return this.Entero1Field;
            }
            set {
                if ((this.Entero1Field.Equals(value) != true)) {
                    this.Entero1Field = value;
                    this.RaisePropertyChanged("Entero1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero2 {
            get {
                return this.Entero2Field;
            }
            set {
                if ((this.Entero2Field.Equals(value) != true)) {
                    this.Entero2Field = value;
                    this.RaisePropertyChanged("Entero2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha1 {
            get {
                return this.Fecha1Field;
            }
            set {
                if ((this.Fecha1Field.Equals(value) != true)) {
                    this.Fecha1Field = value;
                    this.RaisePropertyChanged("Fecha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha2 {
            get {
                return this.Fecha2Field;
            }
            set {
                if ((this.Fecha2Field.Equals(value) != true)) {
                    this.Fecha2Field = value;
                    this.RaisePropertyChanged("Fecha2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico1 {
            get {
                return this.Logico1Field;
            }
            set {
                if ((this.Logico1Field.Equals(value) != true)) {
                    this.Logico1Field = value;
                    this.RaisePropertyChanged("Logico1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico2 {
            get {
                return this.Logico2Field;
            }
            set {
                if ((this.Logico2Field.Equals(value) != true)) {
                    this.Logico2Field = value;
                    this.RaisePropertyChanged("Logico2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modulo {
            get {
                return this.ModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuloField, value) != true)) {
                    this.ModuloField = value;
                    this.RaisePropertyChanged("Modulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCompania {
            get {
                return this.SubCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCompaniaField, value) != true)) {
                    this.SubCompaniaField = value;
                    this.RaisePropertyChanged("SubCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto0 {
            get {
                return this.Texto0Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto0Field, value) != true)) {
                    this.Texto0Field = value;
                    this.RaisePropertyChanged("Texto0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto1 {
            get {
                return this.Texto1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto1Field, value) != true)) {
                    this.Texto1Field = value;
                    this.RaisePropertyChanged("Texto1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto2 {
            get {
                return this.Texto2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto2Field, value) != true)) {
                    this.Texto2Field = value;
                    this.RaisePropertyChanged("Texto2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto3 {
            get {
                return this.Texto3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto3Field, value) != true)) {
                    this.Texto3Field = value;
                    this.RaisePropertyChanged("Texto3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto4 {
            get {
                return this.Texto4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto4Field, value) != true)) {
                    this.Texto4Field = value;
                    this.RaisePropertyChanged("Texto4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UClase {
            get {
                return this.UClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.UClaseField, value) != true)) {
                    this.UClaseField = value;
                    this.RaisePropertyChanged("UClase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public adminlte.TASModuloService.Estado UEstado {
            get {
                return this.UEstadoField;
            }
            set {
                if ((this.UEstadoField.Equals(value) != true)) {
                    this.UEstadoField = value;
                    this.RaisePropertyChanged("UEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool USel {
            get {
                return this.USelField;
            }
            set {
                if ((this.USelField.Equals(value) != true)) {
                    this.USelField = value;
                    this.RaisePropertyChanged("USel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUsuario {
            get {
                return this.UUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UUsuarioField, value) != true)) {
                    this.UUsuarioField = value;
                    this.RaisePropertyChanged("UUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TASModuloService.TASModuloInterface")]
    public interface TASModuloInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebNuevo", ReplyAction="http://tempuri.org/TASModuloInterface/WebNuevoResponse")]
        adminlte.TASModuloService.TASModuloSet WebNuevo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebNuevo", ReplyAction="http://tempuri.org/TASModuloInterface/WebNuevoResponse")]
        System.Threading.Tasks.Task<adminlte.TASModuloService.TASModuloSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebGuardar", ReplyAction="http://tempuri.org/TASModuloInterface/WebGuardarResponse")]
        long WebGuardar(adminlte.TASModuloService.TASModuloSet setTASModulo, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebGuardar", ReplyAction="http://tempuri.org/TASModuloInterface/WebGuardarResponse")]
        System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASModuloService.TASModuloSet setTASModulo, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebEliminar", ReplyAction="http://tempuri.org/TASModuloInterface/WebEliminarResponse")]
        long WebEliminar(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebEliminar", ReplyAction="http://tempuri.org/TASModuloInterface/WebEliminarResponse")]
        System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASModuloInterface/WebEliminarDetalleResponse")]
        long WebEliminarDetalle(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASModuloInterface/WebEliminarDetalleResponse")]
        System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASModuloInterface/WebSeleccionarResponse")]
        adminlte.TASModuloService.TASModuloSet WebSeleccionar(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASModuloInterface/WebSeleccionarResponse")]
        System.Threading.Tasks.Task<adminlte.TASModuloService.TASModuloSet> WebSeleccionarAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASModuloInterface/WebRecalcularResponse")]
        adminlte.TASModuloService.TASModuloSet WebRecalcular(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASModuloInterface/WebRecalcularResponse")]
        System.Threading.Tasks.Task<adminlte.TASModuloService.TASModuloSet> WebRecalcularAsync(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloBloquear", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloBloquearResponse")]
        long WebTASModuloBloquear(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloBloquear", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloBloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASModuloBloquearAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloDesbloquear", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloDesbloquearResponse")]
        long WebTASModuloDesbloquear(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloDesbloquear", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloDesbloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASModuloDesbloquearAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloEsBloqueadoPor", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloEsBloqueadoPorResponse")]
        string WebTASModuloEsBloqueadoPor(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloEsBloqueadoPor", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloEsBloqueadoPorResponse")]
        System.Threading.Tasks.Task<string> WebTASModuloEsBloqueadoPorAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloEsBloqueado", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloEsBloqueadoResponse")]
        bool WebTASModuloEsBloqueado(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloEsBloqueado", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloEsBloqueadoResponse")]
        System.Threading.Tasks.Task<bool> WebTASModuloEsBloqueadoAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionarTodo", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionarTodoResponse")]
        System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity> WebTASModuloSeleccionarTodo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionarTodo", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionarTodoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity>> WebTASModuloSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionar", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionarResponse")]
        System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity> WebTASModuloSeleccionar(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionar", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity>> WebTASModuloSeleccionarAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionarXSubCompaniaResponse" +
            "")]
        System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity> WebTASModuloSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASModuloInterface/WebTASModuloSeleccionarXSubCompaniaResponse" +
            "")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity>> WebTASModuloSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TASModuloInterfaceChannel : adminlte.TASModuloService.TASModuloInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TASModuloInterfaceClient : System.ServiceModel.ClientBase<adminlte.TASModuloService.TASModuloInterface>, adminlte.TASModuloService.TASModuloInterface {
        
        public TASModuloInterfaceClient() {
        }
        
        public TASModuloInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TASModuloInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASModuloInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASModuloInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public adminlte.TASModuloService.TASModuloSet WebNuevo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASModuloService.TASModuloSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevoAsync(strAKASesion, strAKASubCompania);
        }
        
        public long WebGuardar(adminlte.TASModuloService.TASModuloSet setTASModulo, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardar(setTASModulo, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASModuloService.TASModuloSet setTASModulo, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardarAsync(setTASModulo, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminar(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminar(setTASModulo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarAsync(setTASModulo, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminarDetalle(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalle(setTASModulo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalleAsync(setTASModulo, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASModuloService.TASModuloSet WebSeleccionar(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionar(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASModuloService.TASModuloSet> WebSeleccionarAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionarAsync(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASModuloService.TASModuloSet WebRecalcular(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcular(setTASModulo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASModuloService.TASModuloSet> WebRecalcularAsync(adminlte.TASModuloService.TASModuloSet setTASModulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcularAsync(setTASModulo, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASModuloBloquear(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloBloquear(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASModuloBloquearAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloBloquearAsync(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASModuloDesbloquear(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloDesbloquear(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASModuloDesbloquearAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloDesbloquearAsync(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public string WebTASModuloEsBloqueadoPor(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloEsBloqueadoPor(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<string> WebTASModuloEsBloqueadoPorAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloEsBloqueadoPorAsync(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public bool WebTASModuloEsBloqueado(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloEsBloqueado(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<bool> WebTASModuloEsBloqueadoAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloEsBloqueadoAsync(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity> WebTASModuloSeleccionarTodo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloSeleccionarTodo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity>> WebTASModuloSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloSeleccionarTodoAsync(strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity> WebTASModuloSeleccionar(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloSeleccionar(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity>> WebTASModuloSeleccionarAsync(string SubCompania, string Modulo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloSeleccionarAsync(SubCompania, Modulo, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity> WebTASModuloSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloSeleccionarXSubCompania(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASModuloService.TASModuloEntity>> WebTASModuloSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASModuloSeleccionarXSubCompaniaAsync(SubCompania, strAKASesion, strAKASubCompania);
        }
    }
}
