//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.TASEncuestaAlumnoInstructorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASEncuestaAlumnoInstructorSet", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASEncuestaAlumnoInstructorSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity> ltTASEncuestaAlumnoInstructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity> ltTASEncuestaAlumnoInstructorEliminadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> ltTASEncuestaAlumnoInstructorLineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> ltTASEncuestaAlumnoInstructorLineaEliminadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity> ltTASEncuestaAlumnoInstructor {
            get {
                return this.ltTASEncuestaAlumnoInstructorField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASEncuestaAlumnoInstructorField, value) != true)) {
                    this.ltTASEncuestaAlumnoInstructorField = value;
                    this.RaisePropertyChanged("ltTASEncuestaAlumnoInstructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity> ltTASEncuestaAlumnoInstructorEliminado {
            get {
                return this.ltTASEncuestaAlumnoInstructorEliminadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASEncuestaAlumnoInstructorEliminadoField, value) != true)) {
                    this.ltTASEncuestaAlumnoInstructorEliminadoField = value;
                    this.RaisePropertyChanged("ltTASEncuestaAlumnoInstructorEliminado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> ltTASEncuestaAlumnoInstructorLinea {
            get {
                return this.ltTASEncuestaAlumnoInstructorLineaField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASEncuestaAlumnoInstructorLineaField, value) != true)) {
                    this.ltTASEncuestaAlumnoInstructorLineaField = value;
                    this.RaisePropertyChanged("ltTASEncuestaAlumnoInstructorLinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> ltTASEncuestaAlumnoInstructorLineaEliminado {
            get {
                return this.ltTASEncuestaAlumnoInstructorLineaEliminadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASEncuestaAlumnoInstructorLineaEliminadoField, value) != true)) {
                    this.ltTASEncuestaAlumnoInstructorLineaEliminadoField = value;
                    this.RaisePropertyChanged("ltTASEncuestaAlumnoInstructorLineaEliminado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASEncuestaAlumnoInstructorEntity", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASEncuestaAlumnoInstructorEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstructorNroLicenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private adminlte.TASEncuestaAlumnoInstructorService.Estado UEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool USelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal1 {
            get {
                return this.Decimal1Field;
            }
            set {
                if ((this.Decimal1Field.Equals(value) != true)) {
                    this.Decimal1Field = value;
                    this.RaisePropertyChanged("Decimal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal2 {
            get {
                return this.Decimal2Field;
            }
            set {
                if ((this.Decimal2Field.Equals(value) != true)) {
                    this.Decimal2Field = value;
                    this.RaisePropertyChanged("Decimal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero1 {
            get {
                return this.Entero1Field;
            }
            set {
                if ((this.Entero1Field.Equals(value) != true)) {
                    this.Entero1Field = value;
                    this.RaisePropertyChanged("Entero1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero2 {
            get {
                return this.Entero2Field;
            }
            set {
                if ((this.Entero2Field.Equals(value) != true)) {
                    this.Entero2Field = value;
                    this.RaisePropertyChanged("Entero2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha1 {
            get {
                return this.Fecha1Field;
            }
            set {
                if ((this.Fecha1Field.Equals(value) != true)) {
                    this.Fecha1Field = value;
                    this.RaisePropertyChanged("Fecha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha2 {
            get {
                return this.Fecha2Field;
            }
            set {
                if ((this.Fecha2Field.Equals(value) != true)) {
                    this.Fecha2Field = value;
                    this.RaisePropertyChanged("Fecha2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstructorNroLicencia {
            get {
                return this.InstructorNroLicenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorNroLicenciaField, value) != true)) {
                    this.InstructorNroLicenciaField = value;
                    this.RaisePropertyChanged("InstructorNroLicencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico1 {
            get {
                return this.Logico1Field;
            }
            set {
                if ((this.Logico1Field.Equals(value) != true)) {
                    this.Logico1Field = value;
                    this.RaisePropertyChanged("Logico1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico2 {
            get {
                return this.Logico2Field;
            }
            set {
                if ((this.Logico2Field.Equals(value) != true)) {
                    this.Logico2Field = value;
                    this.RaisePropertyChanged("Logico2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materia {
            get {
                return this.MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.MateriaField, value) != true)) {
                    this.MateriaField = value;
                    this.RaisePropertyChanged("Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Programa {
            get {
                return this.ProgramaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramaField, value) != true)) {
                    this.ProgramaField = value;
                    this.RaisePropertyChanged("Programa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCompania {
            get {
                return this.SubCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCompaniaField, value) != true)) {
                    this.SubCompaniaField = value;
                    this.RaisePropertyChanged("SubCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto0 {
            get {
                return this.Texto0Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto0Field, value) != true)) {
                    this.Texto0Field = value;
                    this.RaisePropertyChanged("Texto0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto1 {
            get {
                return this.Texto1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto1Field, value) != true)) {
                    this.Texto1Field = value;
                    this.RaisePropertyChanged("Texto1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto2 {
            get {
                return this.Texto2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto2Field, value) != true)) {
                    this.Texto2Field = value;
                    this.RaisePropertyChanged("Texto2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto3 {
            get {
                return this.Texto3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto3Field, value) != true)) {
                    this.Texto3Field = value;
                    this.RaisePropertyChanged("Texto3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto4 {
            get {
                return this.Texto4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto4Field, value) != true)) {
                    this.Texto4Field = value;
                    this.RaisePropertyChanged("Texto4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UClase {
            get {
                return this.UClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.UClaseField, value) != true)) {
                    this.UClaseField = value;
                    this.RaisePropertyChanged("UClase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public adminlte.TASEncuestaAlumnoInstructorService.Estado UEstado {
            get {
                return this.UEstadoField;
            }
            set {
                if ((this.UEstadoField.Equals(value) != true)) {
                    this.UEstadoField = value;
                    this.RaisePropertyChanged("UEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool USel {
            get {
                return this.USelField;
            }
            set {
                if ((this.USelField.Equals(value) != true)) {
                    this.USelField = value;
                    this.RaisePropertyChanged("USel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUsuario {
            get {
                return this.UUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UUsuarioField, value) != true)) {
                    this.UUsuarioField = value;
                    this.RaisePropertyChanged("UUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASEncuestaAlumnoInstructorLineaEntity", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASEncuestaAlumnoInstructorLineaEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CriterioEvaluacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstudianteLicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstructorNroLicenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionSugerenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PuntuacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private adminlte.TASEncuestaAlumnoInstructorService.Estado UEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CriterioEvaluacion {
            get {
                return this.CriterioEvaluacionField;
            }
            set {
                if ((this.CriterioEvaluacionField.Equals(value) != true)) {
                    this.CriterioEvaluacionField = value;
                    this.RaisePropertyChanged("CriterioEvaluacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstudianteLic {
            get {
                return this.EstudianteLicField;
            }
            set {
                if ((object.ReferenceEquals(this.EstudianteLicField, value) != true)) {
                    this.EstudianteLicField = value;
                    this.RaisePropertyChanged("EstudianteLic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstructorNroLicencia {
            get {
                return this.InstructorNroLicenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorNroLicenciaField, value) != true)) {
                    this.InstructorNroLicenciaField = value;
                    this.RaisePropertyChanged("InstructorNroLicencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Linea {
            get {
                return this.LineaField;
            }
            set {
                if ((this.LineaField.Equals(value) != true)) {
                    this.LineaField = value;
                    this.RaisePropertyChanged("Linea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materia {
            get {
                return this.MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.MateriaField, value) != true)) {
                    this.MateriaField = value;
                    this.RaisePropertyChanged("Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionSugerencia {
            get {
                return this.ObservacionSugerenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionSugerenciaField, value) != true)) {
                    this.ObservacionSugerenciaField = value;
                    this.RaisePropertyChanged("ObservacionSugerencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Programa {
            get {
                return this.ProgramaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramaField, value) != true)) {
                    this.ProgramaField = value;
                    this.RaisePropertyChanged("Programa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Puntuacion {
            get {
                return this.PuntuacionField;
            }
            set {
                if ((this.PuntuacionField.Equals(value) != true)) {
                    this.PuntuacionField = value;
                    this.RaisePropertyChanged("Puntuacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCompania {
            get {
                return this.SubCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCompaniaField, value) != true)) {
                    this.SubCompaniaField = value;
                    this.RaisePropertyChanged("SubCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public adminlte.TASEncuestaAlumnoInstructorService.Estado UEstado {
            get {
                return this.UEstadoField;
            }
            set {
                if ((this.UEstadoField.Equals(value) != true)) {
                    this.UEstadoField = value;
                    this.RaisePropertyChanged("UEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorInterface")]
    public interface TASEncuestaAlumnoInstructorInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebNuevo", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebNuevoResponse")]
        adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet WebNuevo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebNuevo", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebNuevoResponse")]
        System.Threading.Tasks.Task<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebGuardar", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebGuardarResponse")]
        long WebGuardar(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebGuardar", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebGuardarResponse")]
        System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebEliminar", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebEliminarResponse")]
        long WebEliminar(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebEliminar", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebEliminarResponse")]
        System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebEliminarDetalleRespons" +
            "e")]
        long WebEliminarDetalle(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebEliminarDetalleRespons" +
            "e")]
        System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebSeleccionarResponse")]
        adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet WebSeleccionar(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebSeleccionarResponse")]
        System.Threading.Tasks.Task<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet> WebSeleccionarAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebRecalcularResponse")]
        adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet WebRecalcular(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebRecalcularResponse")]
        System.Threading.Tasks.Task<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet> WebRecalcularAsync(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorBloquear", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorBloquearResponse")]
        long WebTASEncuestaAlumnoInstructorBloquear(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorBloquear", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorBloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASEncuestaAlumnoInstructorBloquearAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorDesbloquear", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorDesbloquearResponse")]
        long WebTASEncuestaAlumnoInstructorDesbloquear(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorDesbloquear", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorDesbloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASEncuestaAlumnoInstructorDesbloquearAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorEsBloqueadoPor", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorEsBloqueadoPorResponse")]
        string WebTASEncuestaAlumnoInstructorEsBloqueadoPor(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorEsBloqueadoPor", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorEsBloqueadoPorResponse")]
        System.Threading.Tasks.Task<string> WebTASEncuestaAlumnoInstructorEsBloqueadoPorAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorEsBloqueado", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorEsBloqueadoResponse")]
        bool WebTASEncuestaAlumnoInstructorEsBloqueado(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorEsBloqueado", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorEsBloqueadoResponse")]
        System.Threading.Tasks.Task<bool> WebTASEncuestaAlumnoInstructorEsBloqueadoAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionarTodo", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionarTodoResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity> WebTASEncuestaAlumnoInstructorSeleccionarTodo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionarTodo", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionarTodoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity>> WebTASEncuestaAlumnoInstructorSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionarResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity> WebTASEncuestaAlumnoInstructorSeleccionar(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity>> WebTASEncuestaAlumnoInstructorSeleccionarAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionarXSubCompaniaResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity> WebTASEncuestaAlumnoInstructorSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorSeleccionarXSubCompaniaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity>> WebTASEncuestaAlumnoInstructorSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarTodo", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarTodoResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> WebTASEncuestaAlumnoInstructorLineaSeleccionarTodo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarTodo", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarTodoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity>> WebTASEncuestaAlumnoInstructorLineaSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> WebTASEncuestaAlumnoInstructorLineaSeleccionar(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string EstudianteLic, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity>> WebTASEncuestaAlumnoInstructorLineaSeleccionarAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string EstudianteLic, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarKeyTASEncuestaAlumnoInstructor", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarKeyTASEncuestaAlumnoInstructorResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> WebTASEncuestaAlumnoInstructorLineaSeleccionarKeyTASEncuestaAlumnoInstructor(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarKeyTASEncuestaAlumnoInstructor", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarKeyTASEncuestaAlumnoInstructorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity>> WebTASEncuestaAlumnoInstructorLineaSeleccionarKeyTASEncuestaAlumnoInstructorAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarXSubCompaniaResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> WebTASEncuestaAlumnoInstructorLineaSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASEncuestaAlumnoInstructorInterface/WebTASEncuestaAlumnoInstr" +
            "uctorLineaSeleccionarXSubCompaniaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity>> WebTASEncuestaAlumnoInstructorLineaSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TASEncuestaAlumnoInstructorInterfaceChannel : adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TASEncuestaAlumnoInstructorInterfaceClient : System.ServiceModel.ClientBase<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorInterface>, adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorInterface {
        
        public TASEncuestaAlumnoInstructorInterfaceClient() {
        }
        
        public TASEncuestaAlumnoInstructorInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TASEncuestaAlumnoInstructorInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASEncuestaAlumnoInstructorInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASEncuestaAlumnoInstructorInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet WebNuevo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevoAsync(strAKASesion, strAKASubCompania);
        }
        
        public long WebGuardar(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardar(setTASEncuestaAlumnoInstructor, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardarAsync(setTASEncuestaAlumnoInstructor, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminar(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminar(setTASEncuestaAlumnoInstructor, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarAsync(setTASEncuestaAlumnoInstructor, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminarDetalle(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalle(setTASEncuestaAlumnoInstructor, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalleAsync(setTASEncuestaAlumnoInstructor, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet WebSeleccionar(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionar(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet> WebSeleccionarAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionarAsync(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet WebRecalcular(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcular(setTASEncuestaAlumnoInstructor, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet> WebRecalcularAsync(adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorSet setTASEncuestaAlumnoInstructor, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcularAsync(setTASEncuestaAlumnoInstructor, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASEncuestaAlumnoInstructorBloquear(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorBloquear(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASEncuestaAlumnoInstructorBloquearAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorBloquearAsync(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASEncuestaAlumnoInstructorDesbloquear(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorDesbloquear(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASEncuestaAlumnoInstructorDesbloquearAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorDesbloquearAsync(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public string WebTASEncuestaAlumnoInstructorEsBloqueadoPor(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorEsBloqueadoPor(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<string> WebTASEncuestaAlumnoInstructorEsBloqueadoPorAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorEsBloqueadoPorAsync(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public bool WebTASEncuestaAlumnoInstructorEsBloqueado(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorEsBloqueado(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<bool> WebTASEncuestaAlumnoInstructorEsBloqueadoAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorEsBloqueadoAsync(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity> WebTASEncuestaAlumnoInstructorSeleccionarTodo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorSeleccionarTodo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity>> WebTASEncuestaAlumnoInstructorSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorSeleccionarTodoAsync(strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity> WebTASEncuestaAlumnoInstructorSeleccionar(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorSeleccionar(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity>> WebTASEncuestaAlumnoInstructorSeleccionarAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorSeleccionarAsync(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity> WebTASEncuestaAlumnoInstructorSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorSeleccionarXSubCompania(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorEntity>> WebTASEncuestaAlumnoInstructorSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorSeleccionarXSubCompaniaAsync(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> WebTASEncuestaAlumnoInstructorLineaSeleccionarTodo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorLineaSeleccionarTodo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity>> WebTASEncuestaAlumnoInstructorLineaSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorLineaSeleccionarTodoAsync(strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> WebTASEncuestaAlumnoInstructorLineaSeleccionar(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string EstudianteLic, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorLineaSeleccionar(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, EstudianteLic, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity>> WebTASEncuestaAlumnoInstructorLineaSeleccionarAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string EstudianteLic, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorLineaSeleccionarAsync(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, EstudianteLic, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> WebTASEncuestaAlumnoInstructorLineaSeleccionarKeyTASEncuestaAlumnoInstructor(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorLineaSeleccionarKeyTASEncuestaAlumnoInstructor(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity>> WebTASEncuestaAlumnoInstructorLineaSeleccionarKeyTASEncuestaAlumnoInstructorAsync(string SubCompania, string Programa, string Grupo, string Materia, string InstructorNroLicencia, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorLineaSeleccionarKeyTASEncuestaAlumnoInstructorAsync(SubCompania, Programa, Grupo, Materia, InstructorNroLicencia, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity> WebTASEncuestaAlumnoInstructorLineaSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorLineaSeleccionarXSubCompania(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaAlumnoInstructorService.TASEncuestaAlumnoInstructorLineaEntity>> WebTASEncuestaAlumnoInstructorLineaSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaAlumnoInstructorLineaSeleccionarXSubCompaniaAsync(SubCompania, strAKASesion, strAKASubCompania);
        }
    }
}
