//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.TASMateriaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASMateriaSet", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASMateriaSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity> ltTASMateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity> ltTASMateriaEliminadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity> ltTASMateria {
            get {
                return this.ltTASMateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASMateriaField, value) != true)) {
                    this.ltTASMateriaField = value;
                    this.RaisePropertyChanged("ltTASMateria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity> ltTASMateriaEliminado {
            get {
                return this.ltTASMateriaEliminadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASMateriaEliminadoField, value) != true)) {
                    this.ltTASMateriaEliminadoField = value;
                    this.RaisePropertyChanged("ltTASMateriaEliminado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASMateriaEntity", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASMateriaEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private adminlte.TASMateriaService.Estado UEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool USelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal1 {
            get {
                return this.Decimal1Field;
            }
            set {
                if ((this.Decimal1Field.Equals(value) != true)) {
                    this.Decimal1Field = value;
                    this.RaisePropertyChanged("Decimal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal2 {
            get {
                return this.Decimal2Field;
            }
            set {
                if ((this.Decimal2Field.Equals(value) != true)) {
                    this.Decimal2Field = value;
                    this.RaisePropertyChanged("Decimal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero1 {
            get {
                return this.Entero1Field;
            }
            set {
                if ((this.Entero1Field.Equals(value) != true)) {
                    this.Entero1Field = value;
                    this.RaisePropertyChanged("Entero1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero2 {
            get {
                return this.Entero2Field;
            }
            set {
                if ((this.Entero2Field.Equals(value) != true)) {
                    this.Entero2Field = value;
                    this.RaisePropertyChanged("Entero2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha1 {
            get {
                return this.Fecha1Field;
            }
            set {
                if ((this.Fecha1Field.Equals(value) != true)) {
                    this.Fecha1Field = value;
                    this.RaisePropertyChanged("Fecha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha2 {
            get {
                return this.Fecha2Field;
            }
            set {
                if ((this.Fecha2Field.Equals(value) != true)) {
                    this.Fecha2Field = value;
                    this.RaisePropertyChanged("Fecha2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico1 {
            get {
                return this.Logico1Field;
            }
            set {
                if ((this.Logico1Field.Equals(value) != true)) {
                    this.Logico1Field = value;
                    this.RaisePropertyChanged("Logico1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico2 {
            get {
                return this.Logico2Field;
            }
            set {
                if ((this.Logico2Field.Equals(value) != true)) {
                    this.Logico2Field = value;
                    this.RaisePropertyChanged("Logico2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materia {
            get {
                return this.MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.MateriaField, value) != true)) {
                    this.MateriaField = value;
                    this.RaisePropertyChanged("Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCompania {
            get {
                return this.SubCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCompaniaField, value) != true)) {
                    this.SubCompaniaField = value;
                    this.RaisePropertyChanged("SubCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto0 {
            get {
                return this.Texto0Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto0Field, value) != true)) {
                    this.Texto0Field = value;
                    this.RaisePropertyChanged("Texto0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto1 {
            get {
                return this.Texto1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto1Field, value) != true)) {
                    this.Texto1Field = value;
                    this.RaisePropertyChanged("Texto1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto2 {
            get {
                return this.Texto2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto2Field, value) != true)) {
                    this.Texto2Field = value;
                    this.RaisePropertyChanged("Texto2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto3 {
            get {
                return this.Texto3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto3Field, value) != true)) {
                    this.Texto3Field = value;
                    this.RaisePropertyChanged("Texto3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto4 {
            get {
                return this.Texto4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto4Field, value) != true)) {
                    this.Texto4Field = value;
                    this.RaisePropertyChanged("Texto4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UClase {
            get {
                return this.UClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.UClaseField, value) != true)) {
                    this.UClaseField = value;
                    this.RaisePropertyChanged("UClase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public adminlte.TASMateriaService.Estado UEstado {
            get {
                return this.UEstadoField;
            }
            set {
                if ((this.UEstadoField.Equals(value) != true)) {
                    this.UEstadoField = value;
                    this.RaisePropertyChanged("UEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool USel {
            get {
                return this.USelField;
            }
            set {
                if ((this.USelField.Equals(value) != true)) {
                    this.USelField = value;
                    this.RaisePropertyChanged("USel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUsuario {
            get {
                return this.UUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UUsuarioField, value) != true)) {
                    this.UUsuarioField = value;
                    this.RaisePropertyChanged("UUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TASMateriaService.TASMateriaInterface")]
    public interface TASMateriaInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebNuevo", ReplyAction="http://tempuri.org/TASMateriaInterface/WebNuevoResponse")]
        adminlte.TASMateriaService.TASMateriaSet WebNuevo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebNuevo", ReplyAction="http://tempuri.org/TASMateriaInterface/WebNuevoResponse")]
        System.Threading.Tasks.Task<adminlte.TASMateriaService.TASMateriaSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebGuardar", ReplyAction="http://tempuri.org/TASMateriaInterface/WebGuardarResponse")]
        long WebGuardar(adminlte.TASMateriaService.TASMateriaSet setTASMateria, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebGuardar", ReplyAction="http://tempuri.org/TASMateriaInterface/WebGuardarResponse")]
        System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASMateriaService.TASMateriaSet setTASMateria, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebEliminar", ReplyAction="http://tempuri.org/TASMateriaInterface/WebEliminarResponse")]
        long WebEliminar(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebEliminar", ReplyAction="http://tempuri.org/TASMateriaInterface/WebEliminarResponse")]
        System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASMateriaInterface/WebEliminarDetalleResponse")]
        long WebEliminarDetalle(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASMateriaInterface/WebEliminarDetalleResponse")]
        System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASMateriaInterface/WebSeleccionarResponse")]
        adminlte.TASMateriaService.TASMateriaSet WebSeleccionar(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASMateriaInterface/WebSeleccionarResponse")]
        System.Threading.Tasks.Task<adminlte.TASMateriaService.TASMateriaSet> WebSeleccionarAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASMateriaInterface/WebRecalcularResponse")]
        adminlte.TASMateriaService.TASMateriaSet WebRecalcular(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASMateriaInterface/WebRecalcularResponse")]
        System.Threading.Tasks.Task<adminlte.TASMateriaService.TASMateriaSet> WebRecalcularAsync(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaBloquear", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaBloquearResponse")]
        long WebTASMateriaBloquear(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaBloquear", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaBloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASMateriaBloquearAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaDesbloquear", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaDesbloquearResponse")]
        long WebTASMateriaDesbloquear(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaDesbloquear", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaDesbloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASMateriaDesbloquearAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaEsBloqueadoPor", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaEsBloqueadoPorResponse")]
        string WebTASMateriaEsBloqueadoPor(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaEsBloqueadoPor", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaEsBloqueadoPorResponse")]
        System.Threading.Tasks.Task<string> WebTASMateriaEsBloqueadoPorAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaEsBloqueado", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaEsBloqueadoResponse")]
        bool WebTASMateriaEsBloqueado(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaEsBloqueado", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaEsBloqueadoResponse")]
        System.Threading.Tasks.Task<bool> WebTASMateriaEsBloqueadoAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionarTodo", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionarTodoResponse")]
        System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity> WebTASMateriaSeleccionarTodo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionarTodo", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionarTodoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity>> WebTASMateriaSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionar", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionarResponse")]
        System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity> WebTASMateriaSeleccionar(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionar", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity>> WebTASMateriaSeleccionarAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionarXSubCompaniaRespon" +
            "se")]
        System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity> WebTASMateriaSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASMateriaInterface/WebTASMateriaSeleccionarXSubCompaniaRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity>> WebTASMateriaSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TASMateriaInterfaceChannel : adminlte.TASMateriaService.TASMateriaInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TASMateriaInterfaceClient : System.ServiceModel.ClientBase<adminlte.TASMateriaService.TASMateriaInterface>, adminlte.TASMateriaService.TASMateriaInterface {
        
        public TASMateriaInterfaceClient() {
        }
        
        public TASMateriaInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TASMateriaInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASMateriaInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASMateriaInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public adminlte.TASMateriaService.TASMateriaSet WebNuevo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASMateriaService.TASMateriaSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevoAsync(strAKASesion, strAKASubCompania);
        }
        
        public long WebGuardar(adminlte.TASMateriaService.TASMateriaSet setTASMateria, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardar(setTASMateria, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASMateriaService.TASMateriaSet setTASMateria, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardarAsync(setTASMateria, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminar(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminar(setTASMateria, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarAsync(setTASMateria, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminarDetalle(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalle(setTASMateria, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalleAsync(setTASMateria, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASMateriaService.TASMateriaSet WebSeleccionar(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionar(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASMateriaService.TASMateriaSet> WebSeleccionarAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionarAsync(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASMateriaService.TASMateriaSet WebRecalcular(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcular(setTASMateria, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASMateriaService.TASMateriaSet> WebRecalcularAsync(adminlte.TASMateriaService.TASMateriaSet setTASMateria, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcularAsync(setTASMateria, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASMateriaBloquear(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaBloquear(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASMateriaBloquearAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaBloquearAsync(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASMateriaDesbloquear(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaDesbloquear(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASMateriaDesbloquearAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaDesbloquearAsync(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public string WebTASMateriaEsBloqueadoPor(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaEsBloqueadoPor(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<string> WebTASMateriaEsBloqueadoPorAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaEsBloqueadoPorAsync(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public bool WebTASMateriaEsBloqueado(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaEsBloqueado(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<bool> WebTASMateriaEsBloqueadoAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaEsBloqueadoAsync(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity> WebTASMateriaSeleccionarTodo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaSeleccionarTodo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity>> WebTASMateriaSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaSeleccionarTodoAsync(strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity> WebTASMateriaSeleccionar(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaSeleccionar(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity>> WebTASMateriaSeleccionarAsync(string SubCompania, string Materia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaSeleccionarAsync(SubCompania, Materia, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity> WebTASMateriaSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaSeleccionarXSubCompania(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMateriaService.TASMateriaEntity>> WebTASMateriaSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMateriaSeleccionarXSubCompaniaAsync(SubCompania, strAKASesion, strAKASubCompania);
        }
    }
}
