//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.AdminReglasPlanPagoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdminReglasPlanPagoSet", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class AdminReglasPlanPagoSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity> ltAdminReglasPlanPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity> ltAdminReglasPlanPagoEliminadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity> ltAdminReglasPlanPago {
            get {
                return this.ltAdminReglasPlanPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltAdminReglasPlanPagoField, value) != true)) {
                    this.ltAdminReglasPlanPagoField = value;
                    this.RaisePropertyChanged("ltAdminReglasPlanPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity> ltAdminReglasPlanPagoEliminado {
            get {
                return this.ltAdminReglasPlanPagoEliminadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltAdminReglasPlanPagoEliminadoField, value) != true)) {
                    this.ltAdminReglasPlanPagoEliminadoField = value;
                    this.RaisePropertyChanged("ltAdminReglasPlanPagoEliminado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdminReglasPlanPagoEntity", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class AdminReglasPlanPagoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DiaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DiaIniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoMultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreReglaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private adminlte.AdminReglasPlanPagoService.Estado UEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool USelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal1 {
            get {
                return this.Decimal1Field;
            }
            set {
                if ((this.Decimal1Field.Equals(value) != true)) {
                    this.Decimal1Field = value;
                    this.RaisePropertyChanged("Decimal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal2 {
            get {
                return this.Decimal2Field;
            }
            set {
                if ((this.Decimal2Field.Equals(value) != true)) {
                    this.Decimal2Field = value;
                    this.RaisePropertyChanged("Decimal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DiaFin {
            get {
                return this.DiaFinField;
            }
            set {
                if ((this.DiaFinField.Equals(value) != true)) {
                    this.DiaFinField = value;
                    this.RaisePropertyChanged("DiaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DiaIni {
            get {
                return this.DiaIniField;
            }
            set {
                if ((this.DiaIniField.Equals(value) != true)) {
                    this.DiaIniField = value;
                    this.RaisePropertyChanged("DiaIni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero1 {
            get {
                return this.Entero1Field;
            }
            set {
                if ((this.Entero1Field.Equals(value) != true)) {
                    this.Entero1Field = value;
                    this.RaisePropertyChanged("Entero1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero2 {
            get {
                return this.Entero2Field;
            }
            set {
                if ((this.Entero2Field.Equals(value) != true)) {
                    this.Entero2Field = value;
                    this.RaisePropertyChanged("Entero2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha1 {
            get {
                return this.Fecha1Field;
            }
            set {
                if ((this.Fecha1Field.Equals(value) != true)) {
                    this.Fecha1Field = value;
                    this.RaisePropertyChanged("Fecha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha2 {
            get {
                return this.Fecha2Field;
            }
            set {
                if ((this.Fecha2Field.Equals(value) != true)) {
                    this.Fecha2Field = value;
                    this.RaisePropertyChanged("Fecha2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Linea {
            get {
                return this.LineaField;
            }
            set {
                if ((this.LineaField.Equals(value) != true)) {
                    this.LineaField = value;
                    this.RaisePropertyChanged("Linea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico1 {
            get {
                return this.Logico1Field;
            }
            set {
                if ((this.Logico1Field.Equals(value) != true)) {
                    this.Logico1Field = value;
                    this.RaisePropertyChanged("Logico1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico2 {
            get {
                return this.Logico2Field;
            }
            set {
                if ((this.Logico2Field.Equals(value) != true)) {
                    this.Logico2Field = value;
                    this.RaisePropertyChanged("Logico2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoMulta {
            get {
                return this.MontoMultaField;
            }
            set {
                if ((this.MontoMultaField.Equals(value) != true)) {
                    this.MontoMultaField = value;
                    this.RaisePropertyChanged("MontoMulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRegla {
            get {
                return this.NombreReglaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreReglaField, value) != true)) {
                    this.NombreReglaField = value;
                    this.RaisePropertyChanged("NombreRegla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCompania {
            get {
                return this.SubCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCompaniaField, value) != true)) {
                    this.SubCompaniaField = value;
                    this.RaisePropertyChanged("SubCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto0 {
            get {
                return this.Texto0Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto0Field, value) != true)) {
                    this.Texto0Field = value;
                    this.RaisePropertyChanged("Texto0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto1 {
            get {
                return this.Texto1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto1Field, value) != true)) {
                    this.Texto1Field = value;
                    this.RaisePropertyChanged("Texto1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto2 {
            get {
                return this.Texto2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto2Field, value) != true)) {
                    this.Texto2Field = value;
                    this.RaisePropertyChanged("Texto2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto3 {
            get {
                return this.Texto3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto3Field, value) != true)) {
                    this.Texto3Field = value;
                    this.RaisePropertyChanged("Texto3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto4 {
            get {
                return this.Texto4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto4Field, value) != true)) {
                    this.Texto4Field = value;
                    this.RaisePropertyChanged("Texto4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UClase {
            get {
                return this.UClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.UClaseField, value) != true)) {
                    this.UClaseField = value;
                    this.RaisePropertyChanged("UClase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public adminlte.AdminReglasPlanPagoService.Estado UEstado {
            get {
                return this.UEstadoField;
            }
            set {
                if ((this.UEstadoField.Equals(value) != true)) {
                    this.UEstadoField = value;
                    this.RaisePropertyChanged("UEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool USel {
            get {
                return this.USelField;
            }
            set {
                if ((this.USelField.Equals(value) != true)) {
                    this.USelField = value;
                    this.RaisePropertyChanged("USel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUsuario {
            get {
                return this.UUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UUsuarioField, value) != true)) {
                    this.UUsuarioField = value;
                    this.RaisePropertyChanged("UUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminReglasPlanPagoService.AdminReglasPlanPagoInterface")]
    public interface AdminReglasPlanPagoInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebNuevo", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebNuevoResponse")]
        adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet WebNuevo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebNuevo", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebNuevoResponse")]
        System.Threading.Tasks.Task<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebGuardar", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebGuardarResponse")]
        long WebGuardar(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebGuardar", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebGuardarResponse")]
        System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebEliminar", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebEliminarResponse")]
        long WebEliminar(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebEliminar", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebEliminarResponse")]
        System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebEliminarDetalleResponse")]
        long WebEliminarDetalle(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebEliminarDetalleResponse")]
        System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebSeleccionar", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebSeleccionarResponse")]
        adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet WebSeleccionar(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebSeleccionar", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebSeleccionarResponse")]
        System.Threading.Tasks.Task<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet> WebSeleccionarAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebRecalcular", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebRecalcularResponse")]
        adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet WebRecalcular(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebRecalcular", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebRecalcularResponse")]
        System.Threading.Tasks.Task<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet> WebRecalcularAsync(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoBloquear", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoBloquearRes" +
            "ponse")]
        long WebAdminReglasPlanPagoBloquear(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoBloquear", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoBloquearRes" +
            "ponse")]
        System.Threading.Tasks.Task<long> WebAdminReglasPlanPagoBloquearAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoDesbloquear" +
            "", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoDesbloquear" +
            "Response")]
        long WebAdminReglasPlanPagoDesbloquear(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoDesbloquear" +
            "", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoDesbloquear" +
            "Response")]
        System.Threading.Tasks.Task<long> WebAdminReglasPlanPagoDesbloquearAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoEsBloqueado" +
            "Por", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoEsBloqueado" +
            "PorResponse")]
        string WebAdminReglasPlanPagoEsBloqueadoPor(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoEsBloqueado" +
            "Por", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoEsBloqueado" +
            "PorResponse")]
        System.Threading.Tasks.Task<string> WebAdminReglasPlanPagoEsBloqueadoPorAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoEsBloqueado" +
            "", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoEsBloqueado" +
            "Response")]
        bool WebAdminReglasPlanPagoEsBloqueado(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoEsBloqueado" +
            "", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoEsBloqueado" +
            "Response")]
        System.Threading.Tasks.Task<bool> WebAdminReglasPlanPagoEsBloqueadoAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "Todo", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "TodoResponse")]
        System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity> WebAdminReglasPlanPagoSeleccionarTodo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "Todo", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "TodoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity>> WebAdminReglasPlanPagoSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "Response")]
        System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity> WebAdminReglasPlanPagoSeleccionar(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "Response")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity>> WebAdminReglasPlanPagoSeleccionarAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "XSubCompania", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "XSubCompaniaResponse")]
        System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity> WebAdminReglasPlanPagoSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "XSubCompania", ReplyAction="http://tempuri.org/AdminReglasPlanPagoInterface/WebAdminReglasPlanPagoSeleccionar" +
            "XSubCompaniaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity>> WebAdminReglasPlanPagoSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminReglasPlanPagoInterfaceChannel : adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminReglasPlanPagoInterfaceClient : System.ServiceModel.ClientBase<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoInterface>, adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoInterface {
        
        public AdminReglasPlanPagoInterfaceClient() {
        }
        
        public AdminReglasPlanPagoInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminReglasPlanPagoInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminReglasPlanPagoInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminReglasPlanPagoInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet WebNuevo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevoAsync(strAKASesion, strAKASubCompania);
        }
        
        public long WebGuardar(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardar(setAdminReglasPlanPago, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardarAsync(setAdminReglasPlanPago, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminar(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminar(setAdminReglasPlanPago, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarAsync(setAdminReglasPlanPago, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminarDetalle(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalle(setAdminReglasPlanPago, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalleAsync(setAdminReglasPlanPago, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet WebSeleccionar(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionar(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet> WebSeleccionarAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionarAsync(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet WebRecalcular(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcular(setAdminReglasPlanPago, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet> WebRecalcularAsync(adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoSet setAdminReglasPlanPago, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcularAsync(setAdminReglasPlanPago, strAKASesion, strAKASubCompania);
        }
        
        public long WebAdminReglasPlanPagoBloquear(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoBloquear(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebAdminReglasPlanPagoBloquearAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoBloquearAsync(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public long WebAdminReglasPlanPagoDesbloquear(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoDesbloquear(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebAdminReglasPlanPagoDesbloquearAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoDesbloquearAsync(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public string WebAdminReglasPlanPagoEsBloqueadoPor(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoEsBloqueadoPor(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<string> WebAdminReglasPlanPagoEsBloqueadoPorAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoEsBloqueadoPorAsync(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public bool WebAdminReglasPlanPagoEsBloqueado(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoEsBloqueado(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<bool> WebAdminReglasPlanPagoEsBloqueadoAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoEsBloqueadoAsync(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity> WebAdminReglasPlanPagoSeleccionarTodo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoSeleccionarTodo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity>> WebAdminReglasPlanPagoSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoSeleccionarTodoAsync(strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity> WebAdminReglasPlanPagoSeleccionar(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoSeleccionar(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity>> WebAdminReglasPlanPagoSeleccionarAsync(string SubCompania, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoSeleccionarAsync(SubCompania, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity> WebAdminReglasPlanPagoSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoSeleccionarXSubCompania(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.AdminReglasPlanPagoService.AdminReglasPlanPagoEntity>> WebAdminReglasPlanPagoSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebAdminReglasPlanPagoSeleccionarXSubCompaniaAsync(SubCompania, strAKASesion, strAKASubCompania);
        }
    }
}
