//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASConfiguracionEncuestaSatisfaccionEstudianteSet", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASConfiguracionEncuestaSatisfaccionEstudianteSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity> ltTASConfiguracionEncuestaSatisfaccionEstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity> ltTASConfiguracionEncuestaSatisfaccionEstudianteEliminadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity> ltTASConfiguracionEncuestaSatisfaccionEstudiante {
            get {
                return this.ltTASConfiguracionEncuestaSatisfaccionEstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASConfiguracionEncuestaSatisfaccionEstudianteField, value) != true)) {
                    this.ltTASConfiguracionEncuestaSatisfaccionEstudianteField = value;
                    this.RaisePropertyChanged("ltTASConfiguracionEncuestaSatisfaccionEstudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity> ltTASConfiguracionEncuestaSatisfaccionEstudianteEliminado {
            get {
                return this.ltTASConfiguracionEncuestaSatisfaccionEstudianteEliminadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASConfiguracionEncuestaSatisfaccionEstudianteEliminadoField, value) != true)) {
                    this.ltTASConfiguracionEncuestaSatisfaccionEstudianteEliminadoField = value;
                    this.RaisePropertyChanged("ltTASConfiguracionEncuestaSatisfaccionEstudianteEliminado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASConfiguracionEncuestaSatisfaccionEstudianteEntity", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASConfiguracionEncuestaSatisfaccionEstudianteEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.Estado UEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool USelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal1 {
            get {
                return this.Decimal1Field;
            }
            set {
                if ((this.Decimal1Field.Equals(value) != true)) {
                    this.Decimal1Field = value;
                    this.RaisePropertyChanged("Decimal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal2 {
            get {
                return this.Decimal2Field;
            }
            set {
                if ((this.Decimal2Field.Equals(value) != true)) {
                    this.Decimal2Field = value;
                    this.RaisePropertyChanged("Decimal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero1 {
            get {
                return this.Entero1Field;
            }
            set {
                if ((this.Entero1Field.Equals(value) != true)) {
                    this.Entero1Field = value;
                    this.RaisePropertyChanged("Entero1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero2 {
            get {
                return this.Entero2Field;
            }
            set {
                if ((this.Entero2Field.Equals(value) != true)) {
                    this.Entero2Field = value;
                    this.RaisePropertyChanged("Entero2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha1 {
            get {
                return this.Fecha1Field;
            }
            set {
                if ((this.Fecha1Field.Equals(value) != true)) {
                    this.Fecha1Field = value;
                    this.RaisePropertyChanged("Fecha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha2 {
            get {
                return this.Fecha2Field;
            }
            set {
                if ((this.Fecha2Field.Equals(value) != true)) {
                    this.Fecha2Field = value;
                    this.RaisePropertyChanged("Fecha2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico1 {
            get {
                return this.Logico1Field;
            }
            set {
                if ((this.Logico1Field.Equals(value) != true)) {
                    this.Logico1Field = value;
                    this.RaisePropertyChanged("Logico1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico2 {
            get {
                return this.Logico2Field;
            }
            set {
                if ((this.Logico2Field.Equals(value) != true)) {
                    this.Logico2Field = value;
                    this.RaisePropertyChanged("Logico2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Programa {
            get {
                return this.ProgramaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramaField, value) != true)) {
                    this.ProgramaField = value;
                    this.RaisePropertyChanged("Programa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCompania {
            get {
                return this.SubCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCompaniaField, value) != true)) {
                    this.SubCompaniaField = value;
                    this.RaisePropertyChanged("SubCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto0 {
            get {
                return this.Texto0Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto0Field, value) != true)) {
                    this.Texto0Field = value;
                    this.RaisePropertyChanged("Texto0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto1 {
            get {
                return this.Texto1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto1Field, value) != true)) {
                    this.Texto1Field = value;
                    this.RaisePropertyChanged("Texto1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto2 {
            get {
                return this.Texto2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto2Field, value) != true)) {
                    this.Texto2Field = value;
                    this.RaisePropertyChanged("Texto2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto3 {
            get {
                return this.Texto3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto3Field, value) != true)) {
                    this.Texto3Field = value;
                    this.RaisePropertyChanged("Texto3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto4 {
            get {
                return this.Texto4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto4Field, value) != true)) {
                    this.Texto4Field = value;
                    this.RaisePropertyChanged("Texto4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UClase {
            get {
                return this.UClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.UClaseField, value) != true)) {
                    this.UClaseField = value;
                    this.RaisePropertyChanged("UClase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.Estado UEstado {
            get {
                return this.UEstadoField;
            }
            set {
                if ((this.UEstadoField.Equals(value) != true)) {
                    this.UEstadoField = value;
                    this.RaisePropertyChanged("UEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool USel {
            get {
                return this.USelField;
            }
            set {
                if ((this.USelField.Equals(value) != true)) {
                    this.USelField = value;
                    this.RaisePropertyChanged("USel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUsuario {
            get {
                return this.UUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UUsuarioField, value) != true)) {
                    this.UUsuarioField = value;
                    this.RaisePropertyChanged("UUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSat" +
        "isfaccionEstudianteInterface")]
    public interface TASConfiguracionEncuestaSatisfaccionEstudianteInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebNue" +
            "vo", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebNue" +
            "voResponse")]
        adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet WebNuevo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebNue" +
            "vo", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebNue" +
            "voResponse")]
        System.Threading.Tasks.Task<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebGua" +
            "rdar", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebGua" +
            "rdarResponse")]
        long WebGuardar(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebGua" +
            "rdar", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebGua" +
            "rdarResponse")]
        System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebEli" +
            "minar", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebEli" +
            "minarResponse")]
        long WebEliminar(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebEli" +
            "minar", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebEli" +
            "minarResponse")]
        System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebEli" +
            "minarDetalle", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebEli" +
            "minarDetalleResponse")]
        long WebEliminarDetalle(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebEli" +
            "minarDetalle", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebEli" +
            "minarDetalleResponse")]
        System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebSel" +
            "eccionar", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebSel" +
            "eccionarResponse")]
        adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet WebSeleccionar(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebSel" +
            "eccionar", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebSel" +
            "eccionarResponse")]
        System.Threading.Tasks.Task<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet> WebSeleccionarAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebRec" +
            "alcular", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebRec" +
            "alcularResponse")]
        adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet WebRecalcular(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebRec" +
            "alcular", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebRec" +
            "alcularResponse")]
        System.Threading.Tasks.Task<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet> WebRecalcularAsync(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteBloquear", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteBloquearResponse")]
        long WebTASConfiguracionEncuestaSatisfaccionEstudianteBloquear(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteBloquear", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteBloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASConfiguracionEncuestaSatisfaccionEstudianteBloquearAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteDesbloquear", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteDesbloquearResponse")]
        long WebTASConfiguracionEncuestaSatisfaccionEstudianteDesbloquear(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteDesbloquear", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteDesbloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASConfiguracionEncuestaSatisfaccionEstudianteDesbloquearAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoPor", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoPorResponse")]
        string WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoPor(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoPor", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoPorResponse")]
        System.Threading.Tasks.Task<string> WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoPorAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteEsBloqueado", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoResponse")]
        bool WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueado(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteEsBloqueado", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoResponse")]
        System.Threading.Tasks.Task<bool> WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionarTodo", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionarTodoResponse")]
        System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarTodo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionarTodo", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionarTodoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity>> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionar", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionarResponse")]
        System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionar(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionar", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity>> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionarXSubCompaniaResponse")]
        System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASConfiguracionEncuestaSatisfaccionEstudianteInterface/WebTAS" +
            "ConfiguracionEncuestaSatisfaccionEstudianteSeleccionarXSubCompaniaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity>> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TASConfiguracionEncuestaSatisfaccionEstudianteInterfaceChannel : adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TASConfiguracionEncuestaSatisfaccionEstudianteInterfaceClient : System.ServiceModel.ClientBase<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteInterface>, adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteInterface {
        
        public TASConfiguracionEncuestaSatisfaccionEstudianteInterfaceClient() {
        }
        
        public TASConfiguracionEncuestaSatisfaccionEstudianteInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TASConfiguracionEncuestaSatisfaccionEstudianteInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASConfiguracionEncuestaSatisfaccionEstudianteInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASConfiguracionEncuestaSatisfaccionEstudianteInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet WebNuevo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevoAsync(strAKASesion, strAKASubCompania);
        }
        
        public long WebGuardar(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardar(setTASConfiguracionEncuestaSatisfaccionEstudiante, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardarAsync(setTASConfiguracionEncuestaSatisfaccionEstudiante, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminar(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminar(setTASConfiguracionEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarAsync(setTASConfiguracionEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminarDetalle(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalle(setTASConfiguracionEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalleAsync(setTASConfiguracionEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet WebSeleccionar(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionar(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet> WebSeleccionarAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionarAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet WebRecalcular(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcular(setTASConfiguracionEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet> WebRecalcularAsync(adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteSet setTASConfiguracionEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcularAsync(setTASConfiguracionEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASConfiguracionEncuestaSatisfaccionEstudianteBloquear(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteBloquear(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASConfiguracionEncuestaSatisfaccionEstudianteBloquearAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteBloquearAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASConfiguracionEncuestaSatisfaccionEstudianteDesbloquear(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteDesbloquear(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASConfiguracionEncuestaSatisfaccionEstudianteDesbloquearAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteDesbloquearAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public string WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoPor(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoPor(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<string> WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoPorAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoPorAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public bool WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueado(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueado(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<bool> WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteEsBloqueadoAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarTodo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarTodo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity>> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarTodoAsync(strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionar(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionar(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity>> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarXSubCompania(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASConfiguracionEncuestaSatisfaccionEstudianteService.TASConfiguracionEncuestaSatisfaccionEstudianteEntity>> WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASConfiguracionEncuestaSatisfaccionEstudianteSeleccionarXSubCompaniaAsync(SubCompania, strAKASesion, strAKASubCompania);
        }
    }
}
