//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.TASEstudianteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASEstudianteSet", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASEstudianteSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> ltTASEstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> ltTASEstudianteEliminadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> ltTASEstudiante {
            get {
                return this.ltTASEstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASEstudianteField, value) != true)) {
                    this.ltTASEstudianteField = value;
                    this.RaisePropertyChanged("ltTASEstudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> ltTASEstudianteEliminado {
            get {
                return this.ltTASEstudianteEliminadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASEstudianteEliminadoField, value) != true)) {
                    this.ltTASEstudianteEliminadoField = value;
                    this.RaisePropertyChanged("ltTASEstudianteEliminado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASEstudianteEntity", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASEstudianteEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularTutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoSeguroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomicilioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstudianteCIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExamenPsicofisiologicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExperienciaPreviaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSeguroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InstruccionPreviaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreTutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoFamiliarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private adminlte.TASEstudianteService.Estado UEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool USelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VacunaAntitetanicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido1 {
            get {
                return this.Apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido1Field, value) != true)) {
                    this.Apellido1Field = value;
                    this.RaisePropertyChanged("Apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido2 {
            get {
                return this.Apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido2Field, value) != true)) {
                    this.Apellido2Field = value;
                    this.RaisePropertyChanged("Apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CelularPadre {
            get {
                return this.CelularPadreField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularPadreField, value) != true)) {
                    this.CelularPadreField = value;
                    this.RaisePropertyChanged("CelularPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CelularTutor {
            get {
                return this.CelularTutorField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularTutorField, value) != true)) {
                    this.CelularTutorField = value;
                    this.RaisePropertyChanged("CelularTutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSeguro {
            get {
                return this.CodigoSeguroField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoSeguroField, value) != true)) {
                    this.CodigoSeguroField = value;
                    this.RaisePropertyChanged("CodigoSeguro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTAS {
            get {
                return this.CodigoTASField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTASField, value) != true)) {
                    this.CodigoTASField = value;
                    this.RaisePropertyChanged("CodigoTAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal1 {
            get {
                return this.Decimal1Field;
            }
            set {
                if ((this.Decimal1Field.Equals(value) != true)) {
                    this.Decimal1Field = value;
                    this.RaisePropertyChanged("Decimal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal2 {
            get {
                return this.Decimal2Field;
            }
            set {
                if ((this.Decimal2Field.Equals(value) != true)) {
                    this.Decimal2Field = value;
                    this.RaisePropertyChanged("Decimal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domicilio {
            get {
                return this.DomicilioField;
            }
            set {
                if ((object.ReferenceEquals(this.DomicilioField, value) != true)) {
                    this.DomicilioField = value;
                    this.RaisePropertyChanged("Domicilio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero1 {
            get {
                return this.Entero1Field;
            }
            set {
                if ((this.Entero1Field.Equals(value) != true)) {
                    this.Entero1Field = value;
                    this.RaisePropertyChanged("Entero1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero2 {
            get {
                return this.Entero2Field;
            }
            set {
                if ((this.Entero2Field.Equals(value) != true)) {
                    this.Entero2Field = value;
                    this.RaisePropertyChanged("Entero2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCivil {
            get {
                return this.EstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoCivilField, value) != true)) {
                    this.EstadoCivilField = value;
                    this.RaisePropertyChanged("EstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstudianteCI {
            get {
                return this.EstudianteCIField;
            }
            set {
                if ((object.ReferenceEquals(this.EstudianteCIField, value) != true)) {
                    this.EstudianteCIField = value;
                    this.RaisePropertyChanged("EstudianteCI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExamenPsicofisiologico {
            get {
                return this.ExamenPsicofisiologicoField;
            }
            set {
                if ((this.ExamenPsicofisiologicoField.Equals(value) != true)) {
                    this.ExamenPsicofisiologicoField = value;
                    this.RaisePropertyChanged("ExamenPsicofisiologico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExperienciaPrevia {
            get {
                return this.ExperienciaPreviaField;
            }
            set {
                if ((this.ExperienciaPreviaField.Equals(value) != true)) {
                    this.ExperienciaPreviaField = value;
                    this.RaisePropertyChanged("ExperienciaPrevia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha1 {
            get {
                return this.Fecha1Field;
            }
            set {
                if ((this.Fecha1Field.Equals(value) != true)) {
                    this.Fecha1Field = value;
                    this.RaisePropertyChanged("Fecha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha2 {
            get {
                return this.Fecha2Field;
            }
            set {
                if ((this.Fecha2Field.Equals(value) != true)) {
                    this.Fecha2Field = value;
                    this.RaisePropertyChanged("Fecha2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSeguro {
            get {
                return this.FechaSeguroField;
            }
            set {
                if ((this.FechaSeguroField.Equals(value) != true)) {
                    this.FechaSeguroField = value;
                    this.RaisePropertyChanged("FechaSeguro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InstruccionPrevia {
            get {
                return this.InstruccionPreviaField;
            }
            set {
                if ((this.InstruccionPreviaField.Equals(value) != true)) {
                    this.InstruccionPreviaField = value;
                    this.RaisePropertyChanged("InstruccionPrevia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico1 {
            get {
                return this.Logico1Field;
            }
            set {
                if ((this.Logico1Field.Equals(value) != true)) {
                    this.Logico1Field = value;
                    this.RaisePropertyChanged("Logico1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico2 {
            get {
                return this.Logico2Field;
            }
            set {
                if ((this.Logico2Field.Equals(value) != true)) {
                    this.Logico2Field = value;
                    this.RaisePropertyChanged("Logico2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LugarNacimiento {
            get {
                return this.LugarNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarNacimientoField, value) != true)) {
                    this.LugarNacimientoField = value;
                    this.RaisePropertyChanged("LugarNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nacionalidad {
            get {
                return this.NacionalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadField, value) != true)) {
                    this.NacionalidadField = value;
                    this.RaisePropertyChanged("Nacionalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre1 {
            get {
                return this.Nombre1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre1Field, value) != true)) {
                    this.Nombre1Field = value;
                    this.RaisePropertyChanged("Nombre1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre2 {
            get {
                return this.Nombre2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre2Field, value) != true)) {
                    this.Nombre2Field = value;
                    this.RaisePropertyChanged("Nombre2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePadre {
            get {
                return this.NombrePadreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePadreField, value) != true)) {
                    this.NombrePadreField = value;
                    this.RaisePropertyChanged("NombrePadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTutor {
            get {
                return this.NombreTutorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreTutorField, value) != true)) {
                    this.NombreTutorField = value;
                    this.RaisePropertyChanged("NombreTutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Programa {
            get {
                return this.ProgramaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramaField, value) != true)) {
                    this.ProgramaField = value;
                    this.RaisePropertyChanged("Programa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCompania {
            get {
                return this.SubCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCompaniaField, value) != true)) {
                    this.SubCompaniaField = value;
                    this.RaisePropertyChanged("SubCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoFamiliar {
            get {
                return this.TelefonoFamiliarField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoFamiliarField, value) != true)) {
                    this.TelefonoFamiliarField = value;
                    this.RaisePropertyChanged("TelefonoFamiliar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto0 {
            get {
                return this.Texto0Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto0Field, value) != true)) {
                    this.Texto0Field = value;
                    this.RaisePropertyChanged("Texto0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto1 {
            get {
                return this.Texto1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto1Field, value) != true)) {
                    this.Texto1Field = value;
                    this.RaisePropertyChanged("Texto1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto2 {
            get {
                return this.Texto2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto2Field, value) != true)) {
                    this.Texto2Field = value;
                    this.RaisePropertyChanged("Texto2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto3 {
            get {
                return this.Texto3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto3Field, value) != true)) {
                    this.Texto3Field = value;
                    this.RaisePropertyChanged("Texto3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto4 {
            get {
                return this.Texto4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto4Field, value) != true)) {
                    this.Texto4Field = value;
                    this.RaisePropertyChanged("Texto4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UClase {
            get {
                return this.UClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.UClaseField, value) != true)) {
                    this.UClaseField = value;
                    this.RaisePropertyChanged("UClase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public adminlte.TASEstudianteService.Estado UEstado {
            get {
                return this.UEstadoField;
            }
            set {
                if ((this.UEstadoField.Equals(value) != true)) {
                    this.UEstadoField = value;
                    this.RaisePropertyChanged("UEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool USel {
            get {
                return this.USelField;
            }
            set {
                if ((this.USelField.Equals(value) != true)) {
                    this.USelField = value;
                    this.RaisePropertyChanged("USel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUsuario {
            get {
                return this.UUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UUsuarioField, value) != true)) {
                    this.UUsuarioField = value;
                    this.RaisePropertyChanged("UUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VacunaAntitetanica {
            get {
                return this.VacunaAntitetanicaField;
            }
            set {
                if ((this.VacunaAntitetanicaField.Equals(value) != true)) {
                    this.VacunaAntitetanicaField = value;
                    this.RaisePropertyChanged("VacunaAntitetanica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TASEstudianteService.TASEstudianteInterface")]
    public interface TASEstudianteInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebNuevo", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebNuevoResponse")]
        adminlte.TASEstudianteService.TASEstudianteSet WebNuevo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebNuevo", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebNuevoResponse")]
        System.Threading.Tasks.Task<adminlte.TASEstudianteService.TASEstudianteSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebGuardar", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebGuardarResponse")]
        long WebGuardar(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebGuardar", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebGuardarResponse")]
        System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebEliminar", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebEliminarResponse")]
        long WebEliminar(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebEliminar", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebEliminarResponse")]
        System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebEliminarDetalleResponse")]
        long WebEliminarDetalle(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebEliminarDetalleResponse")]
        System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebSeleccionarResponse")]
        adminlte.TASEstudianteService.TASEstudianteSet WebSeleccionar(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebSeleccionarResponse")]
        System.Threading.Tasks.Task<adminlte.TASEstudianteService.TASEstudianteSet> WebSeleccionarAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebRecalcularResponse")]
        adminlte.TASEstudianteService.TASEstudianteSet WebRecalcular(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebRecalcularResponse")]
        System.Threading.Tasks.Task<adminlte.TASEstudianteService.TASEstudianteSet> WebRecalcularAsync(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteBloquear", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteBloquearResponse")]
        long WebTASEstudianteBloquear(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteBloquear", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteBloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASEstudianteBloquearAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteDesbloquear", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteDesbloquearResponse")]
        long WebTASEstudianteDesbloquear(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteDesbloquear", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteDesbloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASEstudianteDesbloquearAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteEsBloqueadoPor", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteEsBloqueadoPorResponse")]
        string WebTASEstudianteEsBloqueadoPor(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteEsBloqueadoPor", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteEsBloqueadoPorResponse")]
        System.Threading.Tasks.Task<string> WebTASEstudianteEsBloqueadoPorAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteEsBloqueado", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteEsBloqueadoResponse")]
        bool WebTASEstudianteEsBloqueado(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteEsBloqueado", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteEsBloqueadoResponse")]
        System.Threading.Tasks.Task<bool> WebTASEstudianteEsBloqueadoAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarTodo", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarTodoResponse" +
            "")]
        System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> WebTASEstudianteSeleccionarTodo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarTodo", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarTodoResponse" +
            "")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity>> WebTASEstudianteSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionar", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarResponse")]
        System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> WebTASEstudianteSeleccionar(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionar", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity>> WebTASEstudianteSeleccionarAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarXSubCompania" +
            "", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarXSubCompania" +
            "Response")]
        System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> WebTASEstudianteSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarXSubCompania" +
            "", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarXSubCompania" +
            "Response")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity>> WebTASEstudianteSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarXGrupo", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarXGrupoRespon" +
            "se")]
        System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> WebTASEstudianteSeleccionarXGrupo(string SubCompania, string Grupo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarXGrupo", ReplyAction="http://tempuri.org/TASEstudianteInterface/WebTASEstudianteSeleccionarXGrupoRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity>> WebTASEstudianteSeleccionarXGrupoAsync(string SubCompania, string Grupo, string strAKASesion, string strAKASubCompania);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TASEstudianteInterfaceChannel : adminlte.TASEstudianteService.TASEstudianteInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TASEstudianteInterfaceClient : System.ServiceModel.ClientBase<adminlte.TASEstudianteService.TASEstudianteInterface>, adminlte.TASEstudianteService.TASEstudianteInterface {
        
        public TASEstudianteInterfaceClient() {
        }
        
        public TASEstudianteInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TASEstudianteInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASEstudianteInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASEstudianteInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public adminlte.TASEstudianteService.TASEstudianteSet WebNuevo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASEstudianteService.TASEstudianteSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevoAsync(strAKASesion, strAKASubCompania);
        }
        
        public long WebGuardar(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardar(setTASEstudiante, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardarAsync(setTASEstudiante, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminar(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminar(setTASEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarAsync(setTASEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminarDetalle(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalle(setTASEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalleAsync(setTASEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASEstudianteService.TASEstudianteSet WebSeleccionar(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionar(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASEstudianteService.TASEstudianteSet> WebSeleccionarAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionarAsync(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASEstudianteService.TASEstudianteSet WebRecalcular(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcular(setTASEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASEstudianteService.TASEstudianteSet> WebRecalcularAsync(adminlte.TASEstudianteService.TASEstudianteSet setTASEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcularAsync(setTASEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASEstudianteBloquear(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteBloquear(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASEstudianteBloquearAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteBloquearAsync(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASEstudianteDesbloquear(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteDesbloquear(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASEstudianteDesbloquearAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteDesbloquearAsync(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public string WebTASEstudianteEsBloqueadoPor(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteEsBloqueadoPor(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<string> WebTASEstudianteEsBloqueadoPorAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteEsBloqueadoPorAsync(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public bool WebTASEstudianteEsBloqueado(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteEsBloqueado(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<bool> WebTASEstudianteEsBloqueadoAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteEsBloqueadoAsync(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> WebTASEstudianteSeleccionarTodo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteSeleccionarTodo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity>> WebTASEstudianteSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteSeleccionarTodoAsync(strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> WebTASEstudianteSeleccionar(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteSeleccionar(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity>> WebTASEstudianteSeleccionarAsync(string SubCompania, string EstudianteCI, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteSeleccionarAsync(SubCompania, EstudianteCI, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> WebTASEstudianteSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteSeleccionarXSubCompania(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity>> WebTASEstudianteSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteSeleccionarXSubCompaniaAsync(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity> WebTASEstudianteSeleccionarXGrupo(string SubCompania, string Grupo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteSeleccionarXGrupo(SubCompania, Grupo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEstudianteService.TASEstudianteEntity>> WebTASEstudianteSeleccionarXGrupoAsync(string SubCompania, string Grupo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEstudianteSeleccionarXGrupoAsync(SubCompania, Grupo, strAKASesion, strAKASubCompania);
        }
    }
}
