//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.TASMaterialDidacticoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASMaterialDidacticoSet", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASMaterialDidacticoSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity> ltTASMaterialDidacticoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity> ltTASMaterialDidacticoEliminadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity> ltTASMaterialDidactico {
            get {
                return this.ltTASMaterialDidacticoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASMaterialDidacticoField, value) != true)) {
                    this.ltTASMaterialDidacticoField = value;
                    this.RaisePropertyChanged("ltTASMaterialDidactico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity> ltTASMaterialDidacticoEliminado {
            get {
                return this.ltTASMaterialDidacticoEliminadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASMaterialDidacticoEliminadoField, value) != true)) {
                    this.ltTASMaterialDidacticoEliminadoField = value;
                    this.RaisePropertyChanged("ltTASMaterialDidacticoEliminado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASMaterialDidacticoEntity", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASMaterialDidacticoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo14Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo15Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo16Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo17Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo18Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo19Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo20Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo21Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo22Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo23Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo24Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo25Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo26Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo27Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo28Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo29Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Archivo9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstructorNroLicenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Link1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Link2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Link3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Link4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Link5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuloMateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private adminlte.TASMaterialDidacticoService.Estado UEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool USelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo1 {
            get {
                return this.Archivo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo1Field, value) != true)) {
                    this.Archivo1Field = value;
                    this.RaisePropertyChanged("Archivo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo10 {
            get {
                return this.Archivo10Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo10Field, value) != true)) {
                    this.Archivo10Field = value;
                    this.RaisePropertyChanged("Archivo10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo11 {
            get {
                return this.Archivo11Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo11Field, value) != true)) {
                    this.Archivo11Field = value;
                    this.RaisePropertyChanged("Archivo11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo12 {
            get {
                return this.Archivo12Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo12Field, value) != true)) {
                    this.Archivo12Field = value;
                    this.RaisePropertyChanged("Archivo12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo13 {
            get {
                return this.Archivo13Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo13Field, value) != true)) {
                    this.Archivo13Field = value;
                    this.RaisePropertyChanged("Archivo13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo14 {
            get {
                return this.Archivo14Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo14Field, value) != true)) {
                    this.Archivo14Field = value;
                    this.RaisePropertyChanged("Archivo14");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo15 {
            get {
                return this.Archivo15Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo15Field, value) != true)) {
                    this.Archivo15Field = value;
                    this.RaisePropertyChanged("Archivo15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo16 {
            get {
                return this.Archivo16Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo16Field, value) != true)) {
                    this.Archivo16Field = value;
                    this.RaisePropertyChanged("Archivo16");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo17 {
            get {
                return this.Archivo17Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo17Field, value) != true)) {
                    this.Archivo17Field = value;
                    this.RaisePropertyChanged("Archivo17");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo18 {
            get {
                return this.Archivo18Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo18Field, value) != true)) {
                    this.Archivo18Field = value;
                    this.RaisePropertyChanged("Archivo18");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo19 {
            get {
                return this.Archivo19Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo19Field, value) != true)) {
                    this.Archivo19Field = value;
                    this.RaisePropertyChanged("Archivo19");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo2 {
            get {
                return this.Archivo2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo2Field, value) != true)) {
                    this.Archivo2Field = value;
                    this.RaisePropertyChanged("Archivo2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo20 {
            get {
                return this.Archivo20Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo20Field, value) != true)) {
                    this.Archivo20Field = value;
                    this.RaisePropertyChanged("Archivo20");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo21 {
            get {
                return this.Archivo21Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo21Field, value) != true)) {
                    this.Archivo21Field = value;
                    this.RaisePropertyChanged("Archivo21");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo22 {
            get {
                return this.Archivo22Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo22Field, value) != true)) {
                    this.Archivo22Field = value;
                    this.RaisePropertyChanged("Archivo22");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo23 {
            get {
                return this.Archivo23Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo23Field, value) != true)) {
                    this.Archivo23Field = value;
                    this.RaisePropertyChanged("Archivo23");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo24 {
            get {
                return this.Archivo24Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo24Field, value) != true)) {
                    this.Archivo24Field = value;
                    this.RaisePropertyChanged("Archivo24");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo25 {
            get {
                return this.Archivo25Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo25Field, value) != true)) {
                    this.Archivo25Field = value;
                    this.RaisePropertyChanged("Archivo25");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo26 {
            get {
                return this.Archivo26Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo26Field, value) != true)) {
                    this.Archivo26Field = value;
                    this.RaisePropertyChanged("Archivo26");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo27 {
            get {
                return this.Archivo27Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo27Field, value) != true)) {
                    this.Archivo27Field = value;
                    this.RaisePropertyChanged("Archivo27");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo28 {
            get {
                return this.Archivo28Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo28Field, value) != true)) {
                    this.Archivo28Field = value;
                    this.RaisePropertyChanged("Archivo28");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo29 {
            get {
                return this.Archivo29Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo29Field, value) != true)) {
                    this.Archivo29Field = value;
                    this.RaisePropertyChanged("Archivo29");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo3 {
            get {
                return this.Archivo3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo3Field, value) != true)) {
                    this.Archivo3Field = value;
                    this.RaisePropertyChanged("Archivo3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo30 {
            get {
                return this.Archivo30Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo30Field, value) != true)) {
                    this.Archivo30Field = value;
                    this.RaisePropertyChanged("Archivo30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo4 {
            get {
                return this.Archivo4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo4Field, value) != true)) {
                    this.Archivo4Field = value;
                    this.RaisePropertyChanged("Archivo4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo5 {
            get {
                return this.Archivo5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo5Field, value) != true)) {
                    this.Archivo5Field = value;
                    this.RaisePropertyChanged("Archivo5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo6 {
            get {
                return this.Archivo6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo6Field, value) != true)) {
                    this.Archivo6Field = value;
                    this.RaisePropertyChanged("Archivo6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo7 {
            get {
                return this.Archivo7Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo7Field, value) != true)) {
                    this.Archivo7Field = value;
                    this.RaisePropertyChanged("Archivo7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo8 {
            get {
                return this.Archivo8Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo8Field, value) != true)) {
                    this.Archivo8Field = value;
                    this.RaisePropertyChanged("Archivo8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo9 {
            get {
                return this.Archivo9Field;
            }
            set {
                if ((object.ReferenceEquals(this.Archivo9Field, value) != true)) {
                    this.Archivo9Field = value;
                    this.RaisePropertyChanged("Archivo9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal1 {
            get {
                return this.Decimal1Field;
            }
            set {
                if ((this.Decimal1Field.Equals(value) != true)) {
                    this.Decimal1Field = value;
                    this.RaisePropertyChanged("Decimal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal2 {
            get {
                return this.Decimal2Field;
            }
            set {
                if ((this.Decimal2Field.Equals(value) != true)) {
                    this.Decimal2Field = value;
                    this.RaisePropertyChanged("Decimal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero1 {
            get {
                return this.Entero1Field;
            }
            set {
                if ((this.Entero1Field.Equals(value) != true)) {
                    this.Entero1Field = value;
                    this.RaisePropertyChanged("Entero1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero2 {
            get {
                return this.Entero2Field;
            }
            set {
                if ((this.Entero2Field.Equals(value) != true)) {
                    this.Entero2Field = value;
                    this.RaisePropertyChanged("Entero2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha1 {
            get {
                return this.Fecha1Field;
            }
            set {
                if ((this.Fecha1Field.Equals(value) != true)) {
                    this.Fecha1Field = value;
                    this.RaisePropertyChanged("Fecha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha2 {
            get {
                return this.Fecha2Field;
            }
            set {
                if ((this.Fecha2Field.Equals(value) != true)) {
                    this.Fecha2Field = value;
                    this.RaisePropertyChanged("Fecha2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDoc {
            get {
                return this.FechaDocField;
            }
            set {
                if ((this.FechaDocField.Equals(value) != true)) {
                    this.FechaDocField = value;
                    this.RaisePropertyChanged("FechaDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gestion {
            get {
                return this.GestionField;
            }
            set {
                if ((object.ReferenceEquals(this.GestionField, value) != true)) {
                    this.GestionField = value;
                    this.RaisePropertyChanged("Gestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstructorNroLicencia {
            get {
                return this.InstructorNroLicenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorNroLicenciaField, value) != true)) {
                    this.InstructorNroLicenciaField = value;
                    this.RaisePropertyChanged("InstructorNroLicencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link1 {
            get {
                return this.Link1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Link1Field, value) != true)) {
                    this.Link1Field = value;
                    this.RaisePropertyChanged("Link1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link2 {
            get {
                return this.Link2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Link2Field, value) != true)) {
                    this.Link2Field = value;
                    this.RaisePropertyChanged("Link2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link3 {
            get {
                return this.Link3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Link3Field, value) != true)) {
                    this.Link3Field = value;
                    this.RaisePropertyChanged("Link3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link4 {
            get {
                return this.Link4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Link4Field, value) != true)) {
                    this.Link4Field = value;
                    this.RaisePropertyChanged("Link4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link5 {
            get {
                return this.Link5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Link5Field, value) != true)) {
                    this.Link5Field = value;
                    this.RaisePropertyChanged("Link5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico1 {
            get {
                return this.Logico1Field;
            }
            set {
                if ((this.Logico1Field.Equals(value) != true)) {
                    this.Logico1Field = value;
                    this.RaisePropertyChanged("Logico1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico2 {
            get {
                return this.Logico2Field;
            }
            set {
                if ((this.Logico2Field.Equals(value) != true)) {
                    this.Logico2Field = value;
                    this.RaisePropertyChanged("Logico2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materia {
            get {
                return this.MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.MateriaField, value) != true)) {
                    this.MateriaField = value;
                    this.RaisePropertyChanged("Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuloMateria {
            get {
                return this.ModuloMateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuloMateriaField, value) != true)) {
                    this.ModuloMateriaField = value;
                    this.RaisePropertyChanged("ModuloMateria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Programa {
            get {
                return this.ProgramaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramaField, value) != true)) {
                    this.ProgramaField = value;
                    this.RaisePropertyChanged("Programa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCompania {
            get {
                return this.SubCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCompaniaField, value) != true)) {
                    this.SubCompaniaField = value;
                    this.RaisePropertyChanged("SubCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto0 {
            get {
                return this.Texto0Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto0Field, value) != true)) {
                    this.Texto0Field = value;
                    this.RaisePropertyChanged("Texto0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto1 {
            get {
                return this.Texto1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto1Field, value) != true)) {
                    this.Texto1Field = value;
                    this.RaisePropertyChanged("Texto1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto2 {
            get {
                return this.Texto2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto2Field, value) != true)) {
                    this.Texto2Field = value;
                    this.RaisePropertyChanged("Texto2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto3 {
            get {
                return this.Texto3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto3Field, value) != true)) {
                    this.Texto3Field = value;
                    this.RaisePropertyChanged("Texto3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto4 {
            get {
                return this.Texto4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto4Field, value) != true)) {
                    this.Texto4Field = value;
                    this.RaisePropertyChanged("Texto4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UClase {
            get {
                return this.UClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.UClaseField, value) != true)) {
                    this.UClaseField = value;
                    this.RaisePropertyChanged("UClase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public adminlte.TASMaterialDidacticoService.Estado UEstado {
            get {
                return this.UEstadoField;
            }
            set {
                if ((this.UEstadoField.Equals(value) != true)) {
                    this.UEstadoField = value;
                    this.RaisePropertyChanged("UEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool USel {
            get {
                return this.USelField;
            }
            set {
                if ((this.USelField.Equals(value) != true)) {
                    this.USelField = value;
                    this.RaisePropertyChanged("USel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUsuario {
            get {
                return this.UUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UUsuarioField, value) != true)) {
                    this.UUsuarioField = value;
                    this.RaisePropertyChanged("UUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TASMaterialDidacticoService.TASMaterialDidacticoInterface")]
    public interface TASMaterialDidacticoInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebNuevo", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebNuevoResponse")]
        adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet WebNuevo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebNuevo", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebNuevoResponse")]
        System.Threading.Tasks.Task<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebGuardar", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebGuardarResponse")]
        long WebGuardar(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebGuardar", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebGuardarResponse")]
        System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebEliminar", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebEliminarResponse")]
        long WebEliminar(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebEliminar", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebEliminarResponse")]
        System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebEliminarDetalleResponse")]
        long WebEliminarDetalle(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebEliminarDetalleResponse")]
        System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebSeleccionarResponse")]
        adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet WebSeleccionar(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebSeleccionarResponse")]
        System.Threading.Tasks.Task<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet> WebSeleccionarAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebRecalcularResponse")]
        adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet WebRecalcular(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebRecalcularResponse")]
        System.Threading.Tasks.Task<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet> WebRecalcularAsync(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoBloquear", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoBloquearR" +
            "esponse")]
        long WebTASMaterialDidacticoBloquear(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoBloquear", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoBloquearR" +
            "esponse")]
        System.Threading.Tasks.Task<long> WebTASMaterialDidacticoBloquearAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoDesbloque" +
            "ar", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoDesbloque" +
            "arResponse")]
        long WebTASMaterialDidacticoDesbloquear(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoDesbloque" +
            "ar", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoDesbloque" +
            "arResponse")]
        System.Threading.Tasks.Task<long> WebTASMaterialDidacticoDesbloquearAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoEsBloquea" +
            "doPor", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoEsBloquea" +
            "doPorResponse")]
        string WebTASMaterialDidacticoEsBloqueadoPor(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoEsBloquea" +
            "doPor", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoEsBloquea" +
            "doPorResponse")]
        System.Threading.Tasks.Task<string> WebTASMaterialDidacticoEsBloqueadoPorAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoEsBloquea" +
            "do", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoEsBloquea" +
            "doResponse")]
        bool WebTASMaterialDidacticoEsBloqueado(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoEsBloquea" +
            "do", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoEsBloquea" +
            "doResponse")]
        System.Threading.Tasks.Task<bool> WebTASMaterialDidacticoEsBloqueadoAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "arTodo", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "arTodoResponse")]
        System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity> WebTASMaterialDidacticoSeleccionarTodo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "arTodo", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "arTodoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity>> WebTASMaterialDidacticoSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "ar", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "arResponse")]
        System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity> WebTASMaterialDidacticoSeleccionar(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "ar", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "arResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity>> WebTASMaterialDidacticoSeleccionarAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "arXSubCompania", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "arXSubCompaniaResponse")]
        System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity> WebTASMaterialDidacticoSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "arXSubCompania", ReplyAction="http://tempuri.org/TASMaterialDidacticoInterface/WebTASMaterialDidacticoSeleccion" +
            "arXSubCompaniaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity>> WebTASMaterialDidacticoSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TASMaterialDidacticoInterfaceChannel : adminlte.TASMaterialDidacticoService.TASMaterialDidacticoInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TASMaterialDidacticoInterfaceClient : System.ServiceModel.ClientBase<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoInterface>, adminlte.TASMaterialDidacticoService.TASMaterialDidacticoInterface {
        
        public TASMaterialDidacticoInterfaceClient() {
        }
        
        public TASMaterialDidacticoInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TASMaterialDidacticoInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASMaterialDidacticoInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASMaterialDidacticoInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet WebNuevo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevoAsync(strAKASesion, strAKASubCompania);
        }
        
        public long WebGuardar(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardar(setTASMaterialDidactico, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardarAsync(setTASMaterialDidactico, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminar(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminar(setTASMaterialDidactico, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarAsync(setTASMaterialDidactico, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminarDetalle(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalle(setTASMaterialDidactico, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalleAsync(setTASMaterialDidactico, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet WebSeleccionar(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionar(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet> WebSeleccionarAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionarAsync(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet WebRecalcular(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcular(setTASMaterialDidactico, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet> WebRecalcularAsync(adminlte.TASMaterialDidacticoService.TASMaterialDidacticoSet setTASMaterialDidactico, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcularAsync(setTASMaterialDidactico, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASMaterialDidacticoBloquear(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoBloquear(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASMaterialDidacticoBloquearAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoBloquearAsync(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASMaterialDidacticoDesbloquear(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoDesbloquear(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASMaterialDidacticoDesbloquearAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoDesbloquearAsync(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public string WebTASMaterialDidacticoEsBloqueadoPor(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoEsBloqueadoPor(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<string> WebTASMaterialDidacticoEsBloqueadoPorAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoEsBloqueadoPorAsync(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public bool WebTASMaterialDidacticoEsBloqueado(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoEsBloqueado(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<bool> WebTASMaterialDidacticoEsBloqueadoAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoEsBloqueadoAsync(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity> WebTASMaterialDidacticoSeleccionarTodo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoSeleccionarTodo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity>> WebTASMaterialDidacticoSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoSeleccionarTodoAsync(strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity> WebTASMaterialDidacticoSeleccionar(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoSeleccionar(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity>> WebTASMaterialDidacticoSeleccionarAsync(string SubCompania, string Programa, string Grupo, string Materia, string ModuloMateria, string Gestion, string InstructorNroLicencia, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoSeleccionarAsync(SubCompania, Programa, Grupo, Materia, ModuloMateria, Gestion, InstructorNroLicencia, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity> WebTASMaterialDidacticoSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoSeleccionarXSubCompania(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASMaterialDidacticoService.TASMaterialDidacticoEntity>> WebTASMaterialDidacticoSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASMaterialDidacticoSeleccionarXSubCompaniaAsync(SubCompania, strAKASesion, strAKASubCompania);
        }
    }
}
