//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.TASEncuestaSatisfaccionEstudianteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASEncuestaSatisfaccionEstudianteSet", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASEncuestaSatisfaccionEstudianteSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity> ltTASEncuestaSatisfaccionEstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity> ltTASEncuestaSatisfaccionEstudianteEliminadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> ltTASEncuestaSatisfaccionEstudianteLineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> ltTASEncuestaSatisfaccionEstudianteLineaEliminadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity> ltTASEncuestaSatisfaccionEstudiante {
            get {
                return this.ltTASEncuestaSatisfaccionEstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASEncuestaSatisfaccionEstudianteField, value) != true)) {
                    this.ltTASEncuestaSatisfaccionEstudianteField = value;
                    this.RaisePropertyChanged("ltTASEncuestaSatisfaccionEstudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity> ltTASEncuestaSatisfaccionEstudianteEliminado {
            get {
                return this.ltTASEncuestaSatisfaccionEstudianteEliminadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASEncuestaSatisfaccionEstudianteEliminadoField, value) != true)) {
                    this.ltTASEncuestaSatisfaccionEstudianteEliminadoField = value;
                    this.RaisePropertyChanged("ltTASEncuestaSatisfaccionEstudianteEliminado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> ltTASEncuestaSatisfaccionEstudianteLinea {
            get {
                return this.ltTASEncuestaSatisfaccionEstudianteLineaField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASEncuestaSatisfaccionEstudianteLineaField, value) != true)) {
                    this.ltTASEncuestaSatisfaccionEstudianteLineaField = value;
                    this.RaisePropertyChanged("ltTASEncuestaSatisfaccionEstudianteLinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> ltTASEncuestaSatisfaccionEstudianteLineaEliminado {
            get {
                return this.ltTASEncuestaSatisfaccionEstudianteLineaEliminadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ltTASEncuestaSatisfaccionEstudianteLineaEliminadoField, value) != true)) {
                    this.ltTASEncuestaSatisfaccionEstudianteLineaEliminadoField = value;
                    this.RaisePropertyChanged("ltTASEncuestaSatisfaccionEstudianteLineaEliminado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASEncuestaSatisfaccionEstudianteEntity", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASEncuestaSatisfaccionEstudianteEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Decimal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Entero2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Logico2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texto4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private adminlte.TASEncuestaSatisfaccionEstudianteService.Estado UEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool USelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal1 {
            get {
                return this.Decimal1Field;
            }
            set {
                if ((this.Decimal1Field.Equals(value) != true)) {
                    this.Decimal1Field = value;
                    this.RaisePropertyChanged("Decimal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal2 {
            get {
                return this.Decimal2Field;
            }
            set {
                if ((this.Decimal2Field.Equals(value) != true)) {
                    this.Decimal2Field = value;
                    this.RaisePropertyChanged("Decimal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero1 {
            get {
                return this.Entero1Field;
            }
            set {
                if ((this.Entero1Field.Equals(value) != true)) {
                    this.Entero1Field = value;
                    this.RaisePropertyChanged("Entero1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Entero2 {
            get {
                return this.Entero2Field;
            }
            set {
                if ((this.Entero2Field.Equals(value) != true)) {
                    this.Entero2Field = value;
                    this.RaisePropertyChanged("Entero2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha1 {
            get {
                return this.Fecha1Field;
            }
            set {
                if ((this.Fecha1Field.Equals(value) != true)) {
                    this.Fecha1Field = value;
                    this.RaisePropertyChanged("Fecha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha2 {
            get {
                return this.Fecha2Field;
            }
            set {
                if ((this.Fecha2Field.Equals(value) != true)) {
                    this.Fecha2Field = value;
                    this.RaisePropertyChanged("Fecha2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico1 {
            get {
                return this.Logico1Field;
            }
            set {
                if ((this.Logico1Field.Equals(value) != true)) {
                    this.Logico1Field = value;
                    this.RaisePropertyChanged("Logico1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Logico2 {
            get {
                return this.Logico2Field;
            }
            set {
                if ((this.Logico2Field.Equals(value) != true)) {
                    this.Logico2Field = value;
                    this.RaisePropertyChanged("Logico2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Programa {
            get {
                return this.ProgramaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramaField, value) != true)) {
                    this.ProgramaField = value;
                    this.RaisePropertyChanged("Programa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCompania {
            get {
                return this.SubCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCompaniaField, value) != true)) {
                    this.SubCompaniaField = value;
                    this.RaisePropertyChanged("SubCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto0 {
            get {
                return this.Texto0Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto0Field, value) != true)) {
                    this.Texto0Field = value;
                    this.RaisePropertyChanged("Texto0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto1 {
            get {
                return this.Texto1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto1Field, value) != true)) {
                    this.Texto1Field = value;
                    this.RaisePropertyChanged("Texto1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto2 {
            get {
                return this.Texto2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto2Field, value) != true)) {
                    this.Texto2Field = value;
                    this.RaisePropertyChanged("Texto2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto3 {
            get {
                return this.Texto3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto3Field, value) != true)) {
                    this.Texto3Field = value;
                    this.RaisePropertyChanged("Texto3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto4 {
            get {
                return this.Texto4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Texto4Field, value) != true)) {
                    this.Texto4Field = value;
                    this.RaisePropertyChanged("Texto4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UClase {
            get {
                return this.UClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.UClaseField, value) != true)) {
                    this.UClaseField = value;
                    this.RaisePropertyChanged("UClase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public adminlte.TASEncuestaSatisfaccionEstudianteService.Estado UEstado {
            get {
                return this.UEstadoField;
            }
            set {
                if ((this.UEstadoField.Equals(value) != true)) {
                    this.UEstadoField = value;
                    this.RaisePropertyChanged("UEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool USel {
            get {
                return this.USelField;
            }
            set {
                if ((this.USelField.Equals(value) != true)) {
                    this.USelField = value;
                    this.RaisePropertyChanged("USel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUsuario {
            get {
                return this.UUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UUsuarioField, value) != true)) {
                    this.UUsuarioField = value;
                    this.RaisePropertyChanged("UUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TASEncuestaSatisfaccionEstudianteLineaEntity", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    [System.SerializableAttribute()]
    public partial class TASEncuestaSatisfaccionEstudianteLineaEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CriterioEvaluacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstudianteLicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionSugerenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PuntuacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private adminlte.TASEncuestaSatisfaccionEstudianteService.Estado UEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CriterioEvaluacion {
            get {
                return this.CriterioEvaluacionField;
            }
            set {
                if ((this.CriterioEvaluacionField.Equals(value) != true)) {
                    this.CriterioEvaluacionField = value;
                    this.RaisePropertyChanged("CriterioEvaluacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstudianteLic {
            get {
                return this.EstudianteLicField;
            }
            set {
                if ((object.ReferenceEquals(this.EstudianteLicField, value) != true)) {
                    this.EstudianteLicField = value;
                    this.RaisePropertyChanged("EstudianteLic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Linea {
            get {
                return this.LineaField;
            }
            set {
                if ((this.LineaField.Equals(value) != true)) {
                    this.LineaField = value;
                    this.RaisePropertyChanged("Linea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionSugerencia {
            get {
                return this.ObservacionSugerenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionSugerenciaField, value) != true)) {
                    this.ObservacionSugerenciaField = value;
                    this.RaisePropertyChanged("ObservacionSugerencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Programa {
            get {
                return this.ProgramaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramaField, value) != true)) {
                    this.ProgramaField = value;
                    this.RaisePropertyChanged("Programa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Puntuacion {
            get {
                return this.PuntuacionField;
            }
            set {
                if ((this.PuntuacionField.Equals(value) != true)) {
                    this.PuntuacionField = value;
                    this.RaisePropertyChanged("Puntuacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCompania {
            get {
                return this.SubCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCompaniaField, value) != true)) {
                    this.SubCompaniaField = value;
                    this.RaisePropertyChanged("SubCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public adminlte.TASEncuestaSatisfaccionEstudianteService.Estado UEstado {
            get {
                return this.UEstadoField;
            }
            set {
                if ((this.UEstadoField.Equals(value) != true)) {
                    this.UEstadoField = value;
                    this.RaisePropertyChanged("UEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/WebObjetos")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteInterfa" +
        "ce")]
    public interface TASEncuestaSatisfaccionEstudianteInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebNuevo", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebNuevoResponse")]
        adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet WebNuevo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebNuevo", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebNuevoResponse")]
        System.Threading.Tasks.Task<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebGuardar", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebGuardarResponse")]
        long WebGuardar(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebGuardar", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebGuardarResponse")]
        System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebEliminar", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebEliminarResponse" +
            "")]
        long WebEliminar(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebEliminar", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebEliminarResponse" +
            "")]
        System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebEliminarDetalleR" +
            "esponse")]
        long WebEliminarDetalle(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebEliminarDetalle", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebEliminarDetalleR" +
            "esponse")]
        System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebSeleccionarRespo" +
            "nse")]
        adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet WebSeleccionar(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebSeleccionarRespo" +
            "nse")]
        System.Threading.Tasks.Task<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet> WebSeleccionarAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebRecalcularRespon" +
            "se")]
        adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet WebRecalcular(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebRecalcular", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebRecalcularRespon" +
            "se")]
        System.Threading.Tasks.Task<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet> WebRecalcularAsync(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteBloquear", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteBloquearResponse")]
        long WebTASEncuestaSatisfaccionEstudianteBloquear(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteBloquear", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteBloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASEncuestaSatisfaccionEstudianteBloquearAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteDesbloquear", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteDesbloquearResponse")]
        long WebTASEncuestaSatisfaccionEstudianteDesbloquear(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteDesbloquear", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteDesbloquearResponse")]
        System.Threading.Tasks.Task<long> WebTASEncuestaSatisfaccionEstudianteDesbloquearAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteEsBloqueadoPor", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteEsBloqueadoPorResponse")]
        string WebTASEncuestaSatisfaccionEstudianteEsBloqueadoPor(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteEsBloqueadoPor", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteEsBloqueadoPorResponse")]
        System.Threading.Tasks.Task<string> WebTASEncuestaSatisfaccionEstudianteEsBloqueadoPorAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteEsBloqueado", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteEsBloqueadoResponse")]
        bool WebTASEncuestaSatisfaccionEstudianteEsBloqueado(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteEsBloqueado", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteEsBloqueadoResponse")]
        System.Threading.Tasks.Task<bool> WebTASEncuestaSatisfaccionEstudianteEsBloqueadoAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionarTodo", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionarTodoResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity> WebTASEncuestaSatisfaccionEstudianteSeleccionarTodo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionarTodo", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionarTodoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity>> WebTASEncuestaSatisfaccionEstudianteSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionarResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity> WebTASEncuestaSatisfaccionEstudianteSeleccionar(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity>> WebTASEncuestaSatisfaccionEstudianteSeleccionarAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionarXSubCompaniaResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity> WebTASEncuestaSatisfaccionEstudianteSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteSeleccionarXSubCompaniaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity>> WebTASEncuestaSatisfaccionEstudianteSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarTodo", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarTodoResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarTodo(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarTodo", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarTodoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity>> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionar(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string EstudianteLic, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionar", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity>> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string EstudianteLic, long Linea, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarKeyTASEncuestaSatisfaccionEstudiante", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarKeyTASEncuestaSatisfaccionEstudianteResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarKeyTASEncuestaSatisfaccionEstudiante(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarKeyTASEncuestaSatisfaccionEstudiante", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarKeyTASEncuestaSatisfaccionEstudianteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity>> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarKeyTASEncuestaSatisfaccionEstudianteAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarXSubCompaniaResponse")]
        System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarXSubCompania", ReplyAction="http://tempuri.org/TASEncuestaSatisfaccionEstudianteInterface/WebTASEncuestaSatis" +
            "faccionEstudianteLineaSeleccionarXSubCompaniaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity>> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TASEncuestaSatisfaccionEstudianteInterfaceChannel : adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TASEncuestaSatisfaccionEstudianteInterfaceClient : System.ServiceModel.ClientBase<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteInterface>, adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteInterface {
        
        public TASEncuestaSatisfaccionEstudianteInterfaceClient() {
        }
        
        public TASEncuestaSatisfaccionEstudianteInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TASEncuestaSatisfaccionEstudianteInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASEncuestaSatisfaccionEstudianteInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TASEncuestaSatisfaccionEstudianteInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet WebNuevo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet> WebNuevoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebNuevoAsync(strAKASesion, strAKASubCompania);
        }
        
        public long WebGuardar(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardar(setTASEncuestaSatisfaccionEstudiante, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebGuardarAsync(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, bool EsNuevo, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebGuardarAsync(setTASEncuestaSatisfaccionEstudiante, EsNuevo, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminar(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminar(setTASEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarAsync(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarAsync(setTASEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public long WebEliminarDetalle(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalle(setTASEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebEliminarDetalleAsync(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebEliminarDetalleAsync(setTASEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet WebSeleccionar(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionar(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet> WebSeleccionarAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebSeleccionarAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet WebRecalcular(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcular(setTASEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet> WebRecalcularAsync(adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteSet setTASEncuestaSatisfaccionEstudiante, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebRecalcularAsync(setTASEncuestaSatisfaccionEstudiante, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASEncuestaSatisfaccionEstudianteBloquear(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteBloquear(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASEncuestaSatisfaccionEstudianteBloquearAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteBloquearAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public long WebTASEncuestaSatisfaccionEstudianteDesbloquear(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteDesbloquear(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<long> WebTASEncuestaSatisfaccionEstudianteDesbloquearAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteDesbloquearAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public string WebTASEncuestaSatisfaccionEstudianteEsBloqueadoPor(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteEsBloqueadoPor(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<string> WebTASEncuestaSatisfaccionEstudianteEsBloqueadoPorAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteEsBloqueadoPorAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public bool WebTASEncuestaSatisfaccionEstudianteEsBloqueado(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteEsBloqueado(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<bool> WebTASEncuestaSatisfaccionEstudianteEsBloqueadoAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteEsBloqueadoAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity> WebTASEncuestaSatisfaccionEstudianteSeleccionarTodo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteSeleccionarTodo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity>> WebTASEncuestaSatisfaccionEstudianteSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteSeleccionarTodoAsync(strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity> WebTASEncuestaSatisfaccionEstudianteSeleccionar(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteSeleccionar(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity>> WebTASEncuestaSatisfaccionEstudianteSeleccionarAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteSeleccionarAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity> WebTASEncuestaSatisfaccionEstudianteSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteSeleccionarXSubCompania(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteEntity>> WebTASEncuestaSatisfaccionEstudianteSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteSeleccionarXSubCompaniaAsync(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarTodo(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarTodo(strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity>> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarTodoAsync(string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarTodoAsync(strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionar(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string EstudianteLic, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteLineaSeleccionar(SubCompania, Programa, Grupo, Fecha, EstudianteLic, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity>> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string EstudianteLic, long Linea, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarAsync(SubCompania, Programa, Grupo, Fecha, EstudianteLic, Linea, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarKeyTASEncuestaSatisfaccionEstudiante(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarKeyTASEncuestaSatisfaccionEstudiante(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity>> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarKeyTASEncuestaSatisfaccionEstudianteAsync(string SubCompania, string Programa, string Grupo, System.DateTime Fecha, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarKeyTASEncuestaSatisfaccionEstudianteAsync(SubCompania, Programa, Grupo, Fecha, strAKASesion, strAKASubCompania);
        }
        
        public System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarXSubCompania(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarXSubCompania(SubCompania, strAKASesion, strAKASubCompania);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<adminlte.TASEncuestaSatisfaccionEstudianteService.TASEncuestaSatisfaccionEstudianteLineaEntity>> WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarXSubCompaniaAsync(string SubCompania, string strAKASesion, string strAKASubCompania) {
            return base.Channel.WebTASEncuestaSatisfaccionEstudianteLineaSeleccionarXSubCompaniaAsync(SubCompania, strAKASesion, strAKASubCompania);
        }
    }
}
